// ============================================================================
// tests/browser/smoke.spec.js — Home-route browser boot smoke test
//
// Copyright (c) 2026 iHymns. All rights reserved.
//
// WHAT THIS IS
// ------------
// The one thing none of this repo's other test layers can do: load the REAL
// PHP-served SPA shell (appWeb/public_html/index.php) in a REAL browser and
// prove the JS actually boots. `php -l` and ESLint are static — they cannot
// see a CSP header refuse a script, or a browser's real ES-module loader
// 404 on an import. jsdom unit tests never load the real `index.php` output
// at all. Only a real browser hitting the real server exercises the CSP
// header, the module graph, and the parser together — which is exactly
// where #1565's silent-CSP-refusal class of bug lived undetected for ~7
// weeks (see .claude/CLAUDE.md rule #30).
//
// WHAT IT COVERS (first cut — deliberately narrow, see CLAUDE.md rule #34:
// "a solid narrow smoke that always passes/fails deterministically beats a
// broad flaky one")
//   - GET / returns 200 and the SPA shell's stable, always-rendered
//     structural elements are present (#app-header / #main-content /
//     #page-content / #app-footer) — this is TRUE regardless of DB state;
//     see the investigation note below.
//   - The top-level ES module graph (`/js/app.js` and everything it
//     `import`s — ~30 files) loads and executes without a CSP script-src
//     refusal or a module-resolution failure, and `iHymnsApp.init()` runs
//     to completion (`window.iHymnsApp` exists afterwards).
//   - No uncaught `pageerror` (an exception that escaped every try/catch —
//     the sharpest possible "JS failed to boot" signal) at any point during
//     load.
//   - No console `error` other than a short, individually-justified
//     allow-list (see `isKnownBenignConsoleError` below) — anything else is
//     printed in full and fails the test.
//
// WHAT IT DOES NOT COVER YET (tracked as follow-up, not silently skipped)
//   - Any OTHER route (/songbooks, /song/<id>, /search, /manage/*, …).
//   - Actual interactive behaviour (clicking the disclaimer modal, the
//     header dropdowns, search) — this only proves the app boots, not that
//     every feature works. Bootstrap-dependent UI (modals/toasts/dropdowns)
//     is explicitly out of scope here — see the CDN note below.
//   - The service worker / offline path.
//   - Non-Chromium engines.
//
// DB DEPENDENCY (investigated, not assumed — see CLAUDE.md rule #17)
// --------------------------------------------------------------------------
// index.php wraps every DB-touching call in its OG/route-detection block
// (`new SongData()`, `getSongbooks()`, …) in try/catch(\Throwable), and
// `getAppSetting()` (includes/maintenance.php) — which the maintenance-mode
// gate reads before any of that — already returns its default on ANY DB
// error. Confirmed empirically: with appWeb/.auth/db_credentials.php
// deleted entirely, `GET /` still returns 200 with the full shell (header,
// main-content, footer, the `<script type="module" src="/js/app.js">` tag)
// — getDbMysqli() throws, `new SongData()` never completes, `$songData`
// stays undefined, and the later `$songData->getSongbooks()` call throws
// "Call to a member function getSongbooks() on null" — itself just another
// \Throwable the same try/catch swallows, falling back to `[]`. So THIS
// smoke deliberately does not provision a database — the shell + module
// boot is independent of it, and skipping DB setup keeps CI simpler and
// faster. api.php degrades the same way (a DB-down `/api?action=...` calls
// returns a normal small JSON error body, e.g. {"error":"Unable to load
// song data."} — never HTML), so a client-side `fetch(...).then(r=>r.json())`
// never throws either. A later smoke that asserts real data rendered (e.g.
// a specific song's lyrics) WILL need a seeded DB — see Follow-ups below.
//
// THIRD-PARTY CDN NOTE (also investigated, not assumed)
// --------------------------------------------------------------------------
// index.php loads Bootstrap/Font Awesome/jQuery/Animate.css from CDN hosts
// declared in the CSP `script-src`/`style-src` (rule #36's registry), with a
// same-origin `/vendor/...` fallback for exactly the "CDN unreachable"
// case (rule #36's onerror mechanism) — but `appWeb/public_html/vendor/` is
// GENERATED by `tools/download-vendor.sh` at deploy time and is gitignored,
// so a fresh checkout that hasn't run it has NEITHER a reachable CDN (in a
// network-restricted dev/CI sandbox) NOR a local fallback file. In that
// specific combination, the dynamically-inserted fallback `<script src>`
// receives the SPA's own index.php HTML (a same-origin 404 falls through to
// the SPA catch-all — see router.php) instead of a 404, and the browser
// throws a real `SyntaxError: Unexpected token '<'` trying to parse `<!DOCTYPE
// html>` as JavaScript — a genuine uncaught `pageerror`. `ensureVendorStubs()`
// below closes that specific gap (harmless, syntactically-valid stub files,
// written ONLY if the real vendor files aren't already present) so this
// smoke's pass/fail never depends on `tools/download-vendor.sh` having been
// run. It does NOT fix CDN unreachability itself: when the CDN genuinely
// can't be reached, `bootstrap`/`jQuery` stay undefined (Bootstrap-dependent
// UI silently doesn't work), which is why that path is out of scope above.
// `isKnownBenignConsoleError()` allow-lists the resulting noise narrowly —
// see its own comments for exactly what and why. In ordinary CI (GitHub
// Actions has full internet access) the CDN loads succeed and NONE of this
// fires; this only matters in a network-restricted environment.
//
// A pre-existing, separate finding surfaced during this investigation: the
// CDN `<link>`/`<script>` `onerror="…"` fallback attributes in index.php
// have no CSP nonce, so the enforcing CSP (rule #117) refuses to run them
// whenever the primary CDN resource fails — meaning the offline/CDN-down
// fallback rule #36 documents is itself currently silent-broken in that
// exact scenario (the #1565-shaped failure mode: no error the user sees,
// console-only). Deliberately NOT fixed here (out of scope for "add a smoke
// test") — flagged in this PR's summary as a follow-up.
//
// FOLLOW-UPS (suggested, not filed by this change)
//   - Seed a minimal DB and assert a real song/songbook renders end-to-end.
//   - Cover /songbooks and one /song/<id> route.
//   - File the onerror-CSP-nonce gap above as its own issue.
// ============================================================================

import { test, expect } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..', '..');

/**
 * See the "THIRD-PARTY CDN NOTE" above. Writes a syntactically-valid, inert
 * stub ONLY when the real (tools/download-vendor.sh-generated) file isn't
 * already there — never overwrites a real vendor asset.
 */
function ensureVendorStubs() {
    const stubs = [
        [
            'appWeb/public_html/vendor/jquery/jquery.min.js',
            '/* smoke-test stub — real jQuery is fetched by tools/download-vendor.sh at deploy time.\n'
            + '   This file exists only so an unreachable CDN falls back to a harmless no-op\n'
            + '   script instead of index.php\'s own HTML (see smoke.spec.js header). */\n',
        ],
        [
            'appWeb/public_html/vendor/bootstrap/bootstrap.bundle.min.js',
            '/* smoke-test stub — real Bootstrap JS is fetched by tools/download-vendor.sh at deploy\n'
            + '   time. Same rationale as the jquery.min.js stub above. */\n',
        ],
    ];
    for (const [rel, content] of stubs) {
        const abs = path.join(REPO_ROOT, rel);
        if (fs.existsSync(abs)) { continue; }
        fs.mkdirSync(path.dirname(abs), { recursive: true });
        fs.writeFileSync(abs, content);
    }
}

/**
 * Is this console `error` message one of a SHORT, individually-justified
 * list of known-benign entries — as opposed to "we didn't recognise it, so
 * let it through"? Every branch exists because it was observed, understood,
 * and written down; anything that doesn't match is a genuine test failure.
 *
 * @param {import('@playwright/test').ConsoleMessage} msg
 * @param {string[]} thirdPartyHosts hostnames pulled from THIS response's
 *   real CSP header (see thirdPartyHostsFromCsp) — never hand-maintained,
 *   so it can't drift from the policy the server actually sent (rule #34:
 *   derive from the tree, not a list you typed).
 * @returns {boolean}
 */
function isKnownBenignConsoleError(msg, thirdPartyHosts) {
    const text = msg.text();
    const url = msg.location().url || '';

    /* 1. A THIRD-PARTY CDN resource (Bootstrap/jQuery/Font Awesome/
       Animate.css/analytics — exactly the hosts THIS page's own CSP
       script-src/style-src allow-lists, read from the live response, never
       hand-copied) failed to load. That is a network fact about a host we
       don't control, not a defect in this app's own module graph — see the
       "THIRD-PARTY CDN NOTE" above. Scoped to those exact hosts (not "any
       net::ERR_*"), so an unexpected SAME-origin network failure still
       fails the test. */
    if (/^Failed to load resource:/.test(text) && thirdPartyHosts.some((h) => url.includes(h))) {
        return true;
    }

    /* 2. The direct, understood consequence of #1: when the CDN's Bootstrap
       bundle didn't load, `window.bootstrap` is never defined, and
       iHymnsApp.checkDisclaimer() (js/app.js) references it during init.
       app.js's OWN top-level try/catch turns that into a caught, logged,
       non-fatal console.error — confirmed there is never a matching
       `pageerror` for it, i.e. the app keeps running. A third-party-global-
       missing symptom, not a first-party module/CSP boot failure. */
    if (text.includes('[iHymns] Initialisation error') && text.includes('bootstrap is not defined')) {
        return true;
    }

    /* 3. A KNOWN, PRE-EXISTING, narrow CSP gap — see the "A pre-existing,
       separate finding" paragraph above. index.php's CDN <link>/<script>
       tags carry a plain `onerror="…"` attribute with no CSP nonce; the
       enforcing CSP refuses to RUN that inline handler whenever the
       PRIMARY resource failed (i.e. reachable only via case #1 — never
       fires when the CDN loaded, the normal case in real CI). Matched
       NARROWLY to the document itself (not a /js/ script URL), so a CSP
       violation actually blocking our own module graph is never swallowed
       by this branch. Deliberately not fixed here — flagged as a
       follow-up, not silently absorbed. */
    if (text.includes('Refused to execute inline event handler')
        && text.includes('Content Security Policy')
        && !url.includes('/js/')) {
        return true;
    }

    /* 4. ANONYMOUS home-route load: the client optimistically fetches the
       signed-in user's saved preferences (`list_sorts` via the user_settings
       endpoint), and the server CORRECTLY answers 401 for a visitor with no
       session — expected, not a defect. The app catches it and falls back to
       device-local defaults; window.iHymnsApp still constructs and no
       pageerror is thrown (the browser logs the 401 as a resource-load
       console error regardless of the app catching it). This smoke is ALWAYS
       anonymous — it never logs in — so user_settings will ALWAYS 401 here;
       allow-listing it hides no regression THIS smoke could otherwise catch
       (a future authenticated smoke would be its own test). Scoped to the
       user_settings endpoint AND status 401 specifically, so a 401 on any
       OTHER endpoint — a genuine auth/session regression — still fails.
       https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401 */
    if (/Failed to load resource:.*\b401\b/.test(text) && /[?&]action=user_settings\b/.test(url)) {
        return true;
    }

    return false;
}

/** Parse `https://host` origins out of a CSP directive value string. */
function thirdPartyHostsFromCsp(cspHeader) {
    if (!cspHeader) { return []; }
    const hosts = new Set();
    for (const m of cspHeader.matchAll(/https:\/\/([a-z0-9.-]+)/gi)) {
        hosts.add(m[1]);
    }
    return [...hosts];
}

test.beforeAll(() => {
    ensureVendorStubs();
});

test.describe('home route boots', () => {
    test('SPA shell renders and the JS module graph boots cleanly', async ({ page }) => {
        /** @type {import('@playwright/test').ConsoleMessage[]} */
        const consoleErrors = [];
        /** @type {Error[]} */
        const pageErrors = [];

        page.on('console', (msg) => {
            if (msg.type() === 'error') { consoleErrors.push(msg); }
        });
        page.on('pageerror', (err) => { pageErrors.push(err); });

        const response = await page.goto('/', { waitUntil: 'networkidle' });

        expect(response, 'GET / returned no response at all').not.toBeNull();
        expect(response.status(), 'GET / did not return 200').toBe(200);

        /* Give any deferred/microtask-queued init work (module graph
           evaluation, iHymnsApp.init()'s internal await chains) a moment to
           settle beyond `networkidle`, which only tracks network, not JS
           scheduling. Short and fixed — this is a boot check, not a
           feature test with variable-latency data to wait for. */
        await page.waitForTimeout(1000);

        /* --- Structural shell: present regardless of DB state (see header) --- */
        await expect(page.locator('#app-header')).toBeVisible();
        await expect(page.locator('#main-content')).toBeAttached();
        await expect(page.locator('#page-content')).toBeAttached();
        await expect(page.locator('#app-footer')).toBeVisible();
        await expect(page).toHaveTitle(/iHymns/);

        /* --- The actual "did the ES module graph boot" signal: app.js's
           DOMContentLoaded handler constructs `window.iHymnsApp` and calls
           .init() unconditionally (see appWeb/public_html/js/app.js, bottom
           of file) — if any import in the ~30-file graph 404s, throws at
           parse time, or is CSP-refused, this is never reached. --- */
        const appBooted = await page.evaluate(() => typeof window.iHymnsApp === 'object' && window.iHymnsApp !== null);
        expect(appBooted, 'window.iHymnsApp was never constructed — the ES module graph did not finish booting').toBe(true);

        /* --- No uncaught exception, ever. Zero tolerance — this is the
           sharpest "JS failed to boot" signal there is. --- */
        if (pageErrors.length > 0) {
            const details = pageErrors.map((e) => `  - ${e.name}: ${e.message}\n${e.stack || ''}`).join('\n');
            throw new Error(`${pageErrors.length} uncaught pageerror(s) during boot:\n${details}`);
        }

        /* --- Console errors: fail on anything not on the short, justified
           allow-list above. Print every offending message in full so a
           real failure is immediately diagnosable from CI logs alone. --- */
        const cspHeader = response.headers()['content-security-policy'] || '';
        const thirdPartyHosts = thirdPartyHostsFromCsp(cspHeader);
        const unexpected = consoleErrors.filter((m) => !isKnownBenignConsoleError(m, thirdPartyHosts));

        if (unexpected.length > 0) {
            const details = unexpected
                .map((m) => `  - [${m.location().url}:${m.location().lineNumber}] ${m.text()}`)
                .join('\n');
            throw new Error(`${unexpected.length} unexpected console error(s) during boot:\n${details}`);
        }
    });
});
