<?php

declare(strict_types=1);

/**
 * iHymns — Dynamic, per-channel robots.txt (#2024/#2025)
 * ============================================================================
 *
 * ELI5
 * ----
 * robots.txt is the note every search engine reads before it looks at
 * anything else on a site — "here's what you may fetch, and here's where the
 * sitemap is". This used to be one plain text file, identical on all three
 * copies of iHymns and (wrongly) naming ALL THREE channels' sitemaps on
 * every one of them. Now it is generated by PHP, per request, so it can say
 * something different depending on (a) which of the three channels is
 * actually answering — it advertises only ITS OWN sitemap, never the other
 * two's — and (b) whether an admin has switched THIS channel's search-engine
 * visibility off (`/manage/configuration`'s new "Search engine visibility"
 * card) — in which case the `Sitemap:` line simply isn't there any more.
 *
 * DETAILED — WHY THIS REVERSES THE EARLIER "KEEP ROBOTS.TXT STATIC" ADVICE
 * ----------------------------------------------------------------------------
 * The sitemap-hardening pass that preceded this one deliberately recommended
 * AGAINST a dynamic robots.txt — "a static file can never crash". That was
 * right THEN: every channel's content was identical. This feature changes
 * that: the content now differs per channel AND depends on a
 * database-stored admin toggle, which a static file cannot express at all.
 * The risk the old advice was guarding against — a robots.txt that answers a
 * server error — is answered head-on here instead of avoided by staying
 * static: see the NEVER-5xx CONTRACT below. A robots.txt that answers 5xx is
 * genuinely worse than a wrong one — Google treats a server-erroring
 * robots.txt as licence to assume it may crawl NOTHING, and can pause
 * crawling of the whole host.
 *
 * NEVER-5xx CONTRACT (the one hard requirement unique to this file)
 * ----------------------------------------------------------------------------
 * Every branch below answers HTTP 200. The entire body-building section runs
 * inside one `try/catch (\Throwable)`; on ANY failure — including a database
 * outage, since `getAppSetting()` already returns its safe default on any DB
 * error and the only realistic remaining throw source is a programming
 * error — the catch falls back to the SAME base directives, just without a
 * `Sitemap:` line, still 200. That fallback is safe in both directions: for
 * a channel that should be visible, the worst case is a briefly unadvertised
 * sitemap (search engines still discover pages by crawling links); for a
 * hidden channel, the fallback body IS the intended one. No activity-log
 * mirroring here (unlike sitemap.xml.php) — a total try/catch with a safe
 * fallback has no uncaught path left to report; `error_log()` is enough, and
 * keeping this endpoint's OWN moving parts minimal is itself part of the
 * never-5xx posture.
 *
 * THE SEO NUANCE — WHY THE HIDDEN BRANCH NEVER ADDS "Disallow: /"
 * ----------------------------------------------------------------------------
 * noindex (the header/meta this feature also adds — see
 * includes/search_visibility.php) only works on a page a search engine is
 * ALLOWED TO FETCH: it fetches the page, sees "don't index this", and drops
 * it. If robots.txt said `Disallow: /` instead, crawlers would never fetch
 * the page again and would never see the noindex — and a URL they already
 * know about from elsewhere (an old link, a stray backlink) could keep
 * appearing in results as a bare "known page" entry with no description.
 * So a hidden channel's robots.txt stays exactly as permissive as a visible
 * channel's (`Allow: /`, the same `Disallow: /api` / `Disallow: /bridge.html`
 * carve-outs) — the ONLY difference is the missing `Sitemap:` line. This is
 * mechanically enforced: tests/php/test-search-visibility.php PASS 5 bans a
 * bare `Disallow: /` from ever appearing in this file's source.
 *
 * ROUTING: `.htaccess`'s SITEMAP ROUTING section rewrites `/robots.txt` to
 * this file, positioned BEFORE the static-file passthrough — so even if a
 * stale on-disk `robots.txt` is ever left behind by an SFTP deploy that
 * doesn't reliably delete removed files, the rewrite wins and the stale copy
 * is harmless. The static `appWeb/public_html/robots.txt` this file replaces
 * has been deleted from the repo in this same commit — two sources of truth
 * for the same URL would drift.
 *
 * @see appWeb/public_html/includes/search_visibility.php  searchEngineVisibleHere() — the ONE decision this asks
 * @see appWeb/public_html/includes/config.php               appCanonicalHost() (#526) — own-host-only, never a forged Host header
 * @see appWeb/public_html/sitemap.xml.php                   the sitemap's own 404 gate, same helper
 * @see appWeb/public_html/.htaccess                          SITEMAP ROUTING section — the rewrite this relies on
 * @link https://developers.google.com/search/docs/crawling-indexing/robots/intro
 * @link https://developers.google.com/search/docs/crawling-indexing/block-indexing  "why Disallow doesn't remove a page from search"
 */

require_once __DIR__ . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'config.php';
require_once __DIR__ . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'db_mysql.php';
require_once __DIR__ . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'maintenance.php';
require_once __DIR__ . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'search_visibility.php';

header('Content-Type: text/plain; charset=utf-8');
header('X-Content-Type-Options: nosniff');

/* Base directives — identical on every channel, every visibility state.
 * `Allow: /` + the two Disallow carve-outs are preserved verbatim from the
 * original static file; see the SEO-nuance note above for why NO further
 * Disallow line is ever added here, hidden channel or not. */
$body = "User-agent: *\n"
      . "Allow: /\n"
      . "Disallow: /api\n"
      . "Disallow: /bridge.html\n";

try {
    if (searchEngineVisibleHere()) {
        /* Own host only (#526's allow-list, via the shared appCanonicalHost())
         * — this is the fix for the wart the old static file carried: every
         * channel used to advertise all three channels' sitemaps. www.ihymns.app
         * serves from the same production docroot as ihymns.app, so it follows
         * the production toggle and echoes its OWN canonical host here too
         * (consistent with the sitemap itself serving www URLs when requested
         * on www) — no special-casing needed. */
        $scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
        $host   = appCanonicalHost();
        $body  .= "\nSitemap: {$scheme}://{$host}/sitemap.xml\n";
    }
} catch (\Throwable $e) {
    /* Never-5xx contract: fall back to the base directives (no Sitemap line)
       rather than let ANY failure here turn into a 5xx robots.txt. */
    error_log('[robots.txt] falling back to the base directives: ' . $e->getMessage());
}

http_response_code(200);
echo $body;
