<?php
/**
 * Service Worker PHP Wrapper (#81)
 *
 * This file is served as JavaScript but generated by PHP so that
 * the cache version is automatically derived from infoAppVer.php.
 * The .htaccess rule rewrites /service-worker.js → service-worker.js.php.
 *
 * Content-Type is set to JavaScript so the browser treats it correctly.
 *
 * IMPORTANT: This file must ONLY include infoAppVer.php. Including
 * config.php or other files risks PHP errors/warnings that would
 * corrupt the JavaScript output and break service worker registration.
 * CDN URLs are hardcoded here — update them when library versions change.
 */
header('Content-Type: application/javascript; charset=UTF-8');
header('Cache-Control: no-cache, no-store, must-revalidate');
header('Service-Worker-Allowed: /');

/* Hardening (#526) — the file's docblock above warns that PHP errors /
   warnings would corrupt the JS output and break SW registration, but
   previously had no actual handler. If `infoAppVer.php` ever emits a
   notice or a require throws, the SW JS becomes invalid and the
   browser silently fails to register the worker, which silently breaks
   offline mode for every user. Belt-and-braces: trap any error
   *before* it reaches the response, log it, and fall back to a safe
   constant cache key so the SW at least registers (even if the cache
   bucket name is generic). */
$swVersion     = '0.0.0';
$swCommitStamp = '';
$_swPriorErrorHandler = set_error_handler(static function ($severity, $message, $file, $line): bool {
    error_log("[service-worker.php] PHP error during bootstrap: {$message} at {$file}:{$line}");
    return true; /* Suppress — don't allow the warning to leak into the JS body. */
});
try {
    require_once __DIR__ . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'infoAppVer.php';
    $swVersion = $app['Application']['Version']['Number'] ?? '0.0.0';
    /* Fold the commit date (deploy-injected by the GH Actions pipeline) into
       the cache key. Without it every build inside a single semver shares the
       same key and clients stay pinned to the first-installed bundle. Falls
       back to NULL (stripped) during local dev where Commit.Date is unset. */
    $swCommitStamp = preg_replace(
        '/[^0-9]/', '',
        (string)($app['Application']['Version']['Repo']['Commit']['Date'] ?? '')
    );
} catch (\Throwable $e) {
    error_log('[service-worker.php] bootstrap failed; serving SW with generic cache key: ' . $e->getMessage());
} finally {
    /* Restore prior handler (if any) so we don't leak our suppression. */
    restore_error_handler();
}
$swCacheKey = $swCommitStamp !== ''
    ? $swVersion . '-' . $swCommitStamp
    : $swVersion;
?>
/**
 * iHymns — Service Worker
 *
 * Copyright (c) 2026 iHymns. All rights reserved.
 *
 * PURPOSE:
 * Provides offline support and caching for the iHymns PWA.
 *
 * STRATEGY (per-route summary):
 *
 *   ROUTE PATTERN                              STRATEGY
 *   -----------------------------------------  -----------------------------
 *   /                                          network-first (no-store)
 *   /songbooks/, /song/<id>, /tag/<slug>, …    network-first (no-store)
 *   /api?...   (incl. ?page=song, action=*)    network-first (no-store)
 *   /api?action=songs_index (slim index)       network-first (no-store)
 *   CSS / JS / fonts (same-origin)             network-first (no-store)
 *   Trusted CDN (jsdelivr, cdnjs)              network-first (no-store)
 *   /data/audio/*, /data/music/*               cache-first (large media)
 *
 * KEY DESIGN POINT — bypass the browser HTTP cache:
 *
 *   Every network-first branch above uses `fetch(req, { cache: 'no-store' })`
 *   rather than the plain `fetch(req)` it shipped with. Without `no-store`,
 *   the BROWSER'S HTTP CACHE intercepts the request BEFORE the SW gets a
 *   chance to see fresh server data — so a server response with
 *   `Cache-Control: max-age=3600`, OR even a response with NO cache
 *   headers (the browser then heuristic-caches HTML for up to ~10 % of
 *   its age), could be served stale-but-200 to the SW. The SW would
 *   write that stale 200 into its CACHE_VERSION bucket and consider
 *   the round-trip "fresh." Curators on dev.ihymns.app hit this:
 *   after a bulk-import, /songbooks/ kept showing the pre-import list
 *   even after a hard reload AND a manual SW unregister, because the
 *   browser HTTP cache was the real bottleneck.
 *
 *   With `cache: 'no-store'`, the SW always round-trips to the origin
 *   when online. The SW's own CACHE_VERSION bucket remains the single
 *   source of offline-fallback truth — populated only from genuinely
 *   fresh 2xx responses. Media files keep their cache-first strategy
 *   (large binaries, change rarely, no staleness risk).
 *
 * CACHE MANAGEMENT:
 *   - Cache version is derived from infoAppVer.php automatically
 *     (semver × commit-date). Every deploy invalidates older buckets.
 *   - Old caches are automatically cleaned up on activation.
 *   - The dedicated RECENT_CACHE bucket survives version bumps so
 *     downloaded songs remain available offline across upgrades.
 *
 * NOTE: This file is generated by PHP (service-worker.js.php) and served
 * via .htaccess rewrite as /service-worker.js. The PHP wrapper injects
 * the current app version into the CACHE_VERSION constant so it always
 * stays in sync with infoAppVer.php (#81).
 */

/* =========================================================================
 * CACHE CONFIGURATION
 * ========================================================================= */

/**
 * Cache LAYOUT revision (#1597).
 *
 * ELI5: a number we bump ourselves whenever we change which boxes the app
 * keeps things in — separate from the app's own version number.
 *
 * Detail: `$swCacheKey` tracks infoAppVer.php (semver × commit date) and is
 * owned by the deploy pipeline. This constant is owned by THIS file and is
 * bumped whenever the SHAPE of the cache changes (a bucket is added, renamed,
 * or its contents start meaning something different), so a layout change
 * invalidates the versioned buckets even inside one deploy. Bumped 1 → 2 for
 * the #1597 split of deliberate downloads out of the recency bucket.
 */
const SW_CACHE_REVISION = '2';

/**
 * Cache version — derived from the application version AND the deploy-time
 * commit date in infoAppVer.php, plus the layout revision above. The commit
 * date component means every deploy (not just every semver bump) produces a
 * new cache key, so clients pick up fresh module scripts instead of being
 * pinned to the bundle their SW first installed. Old caches are purged on
 * activation (#81).
 */
const CACHE_VERSION = 'ihymns-v<?= $swCacheKey ?>-r' + SW_CACHE_REVISION;

/**
 * Page-fragment cache (#1597 RC3).
 *
 * ELI5: the actual pages — the home screen, the songbook list, a songbook —
 * so you can still move around the app with no signal, not just re-open a
 * song you already had.
 *
 * Detail: before #1597 the SW offline-fell-back ONLY `page=song`, so home /
 * songbooks / songbook / search all 503'd into the red "Failed to load page"
 * card. Even a perfect download was unbrowsable — the only way back to a saved
 * song was history or a bookmark.
 *
 * These fragments are all in api.php's `$_cacheablePages` list, i.e. they are
 * already shared-cache-safe: no per-user data, no per-request nonce (CLAUDE.md
 * rules #6 and #30). The bucket name carries the deploy key so ACTIVATE purges
 * it on every deploy — page markup must never outlive the JS that hydrates it.
 * Contrast RECENT_CACHE / SAVED_CACHE, which deliberately survive deploys
 * because they hold the user's content, not our markup.
 */
const PAGES_CACHE = 'ihymns-pages-v<?= $swCacheKey ?>-r' + SW_CACHE_REVISION;

/**
 * Cap on the page-fragment bucket. `page=search&q=…` is one entry PER QUERY,
 * so without a cap a chatty user grows this without bound inside one deploy
 * window. The trim is confined to this bucket precisely so it can never reach
 * the app shell in CACHE_VERSION (evicting `/js/app.js` to make room for a
 * search result would be a spectacular own goal) — and `swPagesKeysToTrim()`
 * pins the two entry points a user needs in order to browse offline at all.
 */
const PAGES_CACHE_LIMIT = 120;

/**
 * Which `/api?page=…` fragments are worth keeping for offline navigation.
 * Deliberately small: these are the four routes that make a download
 * BROWSABLE. Everything else is either per-user (settings, favourites) or a
 * long tail nobody reaches without a network anyway.
 */
const OFFLINE_PAGE_FRAGMENTS = ['home', 'songbooks', 'songbook', 'search'];

/**
 * Recently-viewed songs cache (#105).
 *
 * ELI5: the last couple of thousand songs you happened to look at. The app
 * tidies this up on its own — oldest out first.
 *
 * Detail: written by the `CACHE_SONG` message router.js posts on EVERY song
 * view. Capped, and trimmed oldest-first on each write. Separate bucket from
 * CACHE_VERSION so it survives app version purges.
 */
const RECENT_CACHE = 'ihymns-recent-songs';
const RECENT_CACHE_LIMIT = 2000;

/**
 * Deliberately-downloaded songs cache (#1597 RC1) — THE fix at the heart of
 * this issue.
 *
 * ELI5: the songs you actually asked to download. They live in their own box
 * that the automatic tidy-up is never allowed to open.
 *
 * Detail: before #1597 bulk downloads and incidental views shared ONE bucket
 * and ONE 2000-entry budget. Download Mission Praise (3,517 songs), then open
 * a single song — the `CACHE_SONG` handler's trim ran and deleted ~1,500
 * entries of the download the UI had just reported as complete. The user found
 * out on a plane.
 *
 * Bulk-saved and recently-viewed are DIFFERENT INTENTS and must not share a
 * cap: a recency cache is a convenience the app may reclaim at will, whereas a
 * download is a promise. So deliberate saves land here and NOTHING in the SW
 * trims this bucket — it shrinks only when the user explicitly asks, via
 * `EVICT_SONGBOOK`, or when the browser evicts the whole origin (which
 * `navigator.storage.persist()` in offline-ui.js now argues against, RC6).
 *
 * Intent is carried on the message: `{ type: 'CACHE_SONG', url, saved: true }`
 * from the Download buttons, and no flag at all from router.js's automatic
 * view-caching — so the DEFAULT stays "recency", and router.js needs no change.
 */
const SAVED_CACHE = 'ihymns-saved-songs';

/**
 * Audio + sheet-music cache (#401).
 *
 * ELI5: the box the actual music files go in.
 *
 * Detail: the name is UNCHANGED from the pre-#1597 tree on purpose. Renaming
 * it would make the very commit that fixes "every deploy wipes your audio"
 * wipe everyone's audio one final time. It was never in the activate keep-list
 * (#1597 RC2), so every SW activation — i.e. every deploy, and the version now
 * bumps on every alpha push (#1596) — deleted the lot while the UI still
 * showed the songbook as saved.
 */
const MEDIA_CACHE = 'iHymns-media-v1';

/**
 * One-time migration marker for the #1597 RECENT → SAVED split.
 * Parked inside SAVED_CACHE so it is naturally scoped to the bucket it
 * describes. Deliberately shaped as a path with NO `id` query parameter, so
 * every consumer that reads a songbook out of a cache key
 * (`swSongbookFromSongCacheUrl`) resolves it to null and skips it — it is
 * never evicted, never counted towards a songbook's size, and never mistaken
 * for a song.
 */
const SAVED_SPLIT_SENTINEL = '/__ihymns_sw__/saved-split-v1';

/* =========================================================================
 * CACHE POLICY HELPERS (#1597)
 *
 * Every one of these is PURE — same input, same output, no I/O, no globals
 * beyond `self.location.origin`. That is deliberate: the cache policy is what
 * silently destroyed users' downloads for months, and a pure function is a
 * function `tests/test-offline-cache-policy.js` can call directly. That suite
 * strips the PHP head off this file and evaluates the REAL body, so the test
 * exercises the shipped decision logic rather than a paraphrase of it.
 * ========================================================================= */

/**
 * Every cache bucket that must SURVIVE an activate.
 *
 * ELI5: the list of boxes the spring-clean is not allowed to throw away.
 *
 * Detail: the pre-#1597 activate handler inlined this as
 * `name !== CACHE_VERSION && name !== RECENT_CACHE`, which silently omitted
 * the audio bucket — so every deploy deleted every downloaded MP3 (RC2).
 * Naming the list in one place means a future bucket is added HERE, once,
 * rather than being forgotten in a boolean chain.
 *
 * @returns {string[]}
 */
function swKeptCacheNames() {
    return [CACHE_VERSION, PAGES_CACHE, RECENT_CACHE, SAVED_CACHE, MEDIA_CACHE];
}

/**
 * Should this cache bucket survive activation?
 * @param {string} name Cache bucket name from caches.keys()
 * @returns {boolean}
 */
function swIsCacheKept(name) {
    return swKeptCacheNames().indexOf(name) !== -1;
}

/**
 * Which bucket does a song page belong in?
 *
 * @param {boolean} [saved] True when the user DELIBERATELY asked to keep this
 *   song (a Download button). Absent/false = incidental view from router.js,
 *   which is the default precisely so router.js needs no change (#1597 RC1).
 * @returns {string} Cache bucket name
 */
function swSongCacheName(saved) {
    return saved === true ? SAVED_CACHE : RECENT_CACHE;
}

/**
 * The oldest keys to delete so a bucket fits its cap.
 *
 * ELI5: when the box is too full, take the things that went in first back out.
 *
 * Detail: Cache.keys() resolves in INSERTION order, so `slice(0, excess)` is
 * oldest-first. Callers must only ever hand this the keys of the RECENCY
 * bucket — SAVED_CACHE is never trimmed, which is the whole point of RC1.
 * https://developer.mozilla.org/en-US/docs/Web/API/Cache/keys
 *
 * @param {Array<Request|{url:string}>} keys
 * @param {number} limit
 * @returns {Array} The subset to delete (empty when under the cap)
 */
function swKeysToTrim(keys, limit) {
    const excess = keys.length - limit;
    return excess > 0 ? keys.slice(0, excess) : [];
}

/**
 * The page fragments to delete so the fragment bucket fits its cap.
 *
 * Same oldest-first rule as swKeysToTrim(), except `page=home` and
 * `page=songbooks` are PINNED: they are the two entry points a user needs in
 * order to browse offline at all, and evicting them to make room for the 121st
 * search result would re-create RC3 by the back door.
 *
 * @param {Array<Request|{url:string}>} keys
 * @param {number} limit
 * @returns {Array} The subset to delete
 */
function swPagesKeysToTrim(keys, limit) {
    const excess = keys.length - limit;
    if (excess <= 0) return [];
    const pinned = ['home', 'songbooks'];
    return keys
        .filter(k => pinned.indexOf(swOfflinePageFragment(k && k.url ? k.url : k)) === -1)
        .slice(0, excess);
}

/**
 * Is this URL an `/api?page=…` fragment worth keeping for offline navigation?
 *
 * @param {string} rawUrl Absolute or root-relative URL
 * @returns {string|null} The page name, or null when it isn't one
 */
function swOfflinePageFragment(rawUrl) {
    try {
        const u = new URL(rawUrl, self.location.origin);
        if (!u.pathname.startsWith('/api')) return null;
        const page = u.searchParams.get('page');
        return OFFLINE_PAGE_FRAGMENTS.indexOf(page) !== -1 ? page : null;
    } catch {
        /* A caller can hand us anything the Cache API stored; never throw
           from inside an activate/message handler over a malformed key. */
        return null;
    }
}

/**
 * Songbook abbreviation for a cached SONG PAGE key (`/api?page=song&id=MP-1008`).
 * @param {string} rawUrl
 * @returns {string|null} Upper-cased abbreviation, or null
 */
function swSongbookFromSongCacheUrl(rawUrl) {
    try {
        const id = new URL(rawUrl, self.location.origin).searchParams.get('id') || '';
        const dash = id.indexOf('-');
        return dash > 0 ? id.slice(0, dash).toUpperCase() : null;
    } catch {
        return null;
    }
}

/**
 * Songbook abbreviation for a cached MEDIA key (#1597 RC4).
 *
 * ELI5: works out which songbook an audio file belongs to by reading its
 * filename, because that is where the answer actually is.
 *
 * Detail: the pre-#1597 code matched `/data/audio/<book>/…` SUBDIRECTORIES —
 * a layout this app has never used. `api.php`'s `bulk_audio` emits the FLAT
 * `/data/audio/<SongId>.mp3` (api.php:1517), sheet music is the flat
 * `/data/music/<SongId>.pdf` (sheet-music.js:20), and the gated route is the
 * flat `/audio/<SongId>.mp3?exp=…&sig=…` (#1358). So the directory regex
 * matched NOTHING: "Remove from offline" silently removed no audio at all and
 * the reported size was wrong, both while reporting success.
 *
 * The songbook is recovered from the SongId prefix instead, which CLAUDE.md
 * rule #27 guarantees is `<letters>-<digits>`. The optional directory group is
 * kept so a hypothetical nested layout still resolves.
 *
 * @param {string} rawUrl
 * @returns {string|null} Upper-cased abbreviation, or null
 */
function swSongbookFromMediaUrl(rawUrl) {
    let pathname;
    try {
        pathname = new URL(rawUrl, self.location.origin).pathname;
    } catch {
        return null;
    }
    /* /data/audio/… | /data/music/… | /audio/… , an OPTIONAL <dir>/, then
       <basename>.<ext>. The query string is already gone — URL.pathname
       excludes it — so a signed ?exp=…&sig=… URL matches like any other. */
    const m = pathname.match(/^\/(?:data\/audio|data\/music|audio)\/(?:([^/]+)\/)?([^/]+)\.[A-Za-z0-9]+$/);
    if (!m) return null;
    /* Legacy nested layout: the directory IS the songbook. */
    if (m[1]) return m[1].toUpperCase();
    /* Flat layout: derive it from the SongId prefix. rawurlencode() leaves an
       alphanumeric-plus-dash SongId untouched, but decode defensively so an
       escaped key still resolves. */
    let base = m[2];
    try { base = decodeURIComponent(base); } catch { /* keep the raw form */ }
    const dash = base.indexOf('-');
    if (dash <= 0) return null;
    /* Only <letters>-<digits> is a SongId (rule #27); anything else is some
       other file that happens to contain a dash. */
    if (!/^[A-Za-z0-9]+-\d+$/.test(base)) return null;
    return base.slice(0, dash).toUpperCase();
}

/**
 * Assets to pre-cache during service worker installation.
 * These are the essential app shell files needed for offline access.
 */
const PRECACHE_ASSETS = [
    '/',
    '/css/app.css',
    '/css/accessibility.css',
    '/css/print.css',
    '/js/app.js',
    '/js/constants.js',
    '/js/utils/html.js',
    '/js/utils/components.js',
    '/js/utils/text.js',
    '/js/utils/song-existence.js',
    '/js/modules/router.js',
    '/js/modules/transitions.js',
    '/js/modules/settings.js',
    '/js/modules/search.js',
    '/js/modules/favorites.js',
    '/js/modules/pwa.js',
    '/js/modules/shuffle.js',
    '/js/modules/numpad.js',
    '/js/modules/share.js',
    '/js/modules/compare.js',
    '/js/modules/live-follow.js',
    '/js/modules/service-follow.js',
    '/js/modules/shortcuts.js',
    '/js/modules/request.js',
    '/js/modules/transpose.js',
    '/js/modules/reading-progress.js',
    '/js/modules/songbook-index.js',
    '/js/modules/search-history.js',
    '/js/modules/song-of-the-day.js',
    '/js/modules/offline-indicator.js',
    '/js/modules/storage-bridge.js',
    '/js/modules/subdomain-sync.js',
    '/js/modules/display.js',
    '/js/modules/audio.js',
    '/js/modules/sheet-music.js',
    '/js/modules/history.js',
    '/js/modules/setlist.js',
    '/js/modules/user-auth.js',
    '/js/modules/gestures.js',
    '/js/modules/analytics.js',
    '/js/modules/offline-queue.js',
    '/js/modules/notifications.js',
    '/js/modules/home-page.js',
    '/js/modules/offline-ui.js',
    '/js/modules/entitlements.js',
    '/manifest.json',
    '/assets/favicon.svg',
];

/**
 * Best-effort precache list (#354). Items here are fetched at install
 * time but failures don't block SW activation. Used for URLs that may
 * be slow or unreliable but are valuable to have warm-cached:
 *   - /api?action=songs_index — the SLIM catalogue index (WS-I #1017):
 *     id/number/title/songbook per song, a few hundred KB gzipped (vs the
 *     ~5.7 MB whole-song corpus we used to precache). It lets a user who
 *     installs the PWA, browses only the home page, then goes offline,
 *     still browse + run a basic title/number search (the client-side
 *     offline fallback in search.js). Online, every read is still live;
 *     this index is the OFFLINE-ONLY fallback.
 *
 * We intentionally do NOT put this in PRECACHE_ASSETS (which is strict)
 * because it would fail the entire SW install if the endpoint is slow
 * on the install-tab's network.
 */
const PRECACHE_BEST_EFFORT_ASSETS = [
    '/api?action=songs_index',
];

/**
 * Trusted CDN origins whose resources are cached for offline use.
 * These CDNs serve CORS headers (Access-Control-Allow-Origin: *)
 * so responses can be cached and later served with SRI verification.
 */
const TRUSTED_CDN_ORIGINS = [
    'https://cdn.jsdelivr.net',
    'https://cdnjs.cloudflare.com',
];

/**
 * Critical CDN assets to pre-cache during install for offline app shell.
 * Hardcoded here (not injected from config.php) to avoid any risk of PHP
 * errors corrupting the JS output and breaking SW registration.
 * UPDATE THESE when library versions change in config.php.
 */
const PRECACHE_CDN_ASSETS = [
    'https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css',
    'https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js',
    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css',
    'https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js',
    'https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css',
];

/**
 * Local vendor fallback paths — pre-cached best-effort.
 * These files are served when CDN resources are unavailable and the
 * CDN cache is also empty (e.g., first offline launch after install).
 */
const PRECACHE_VENDOR_ASSETS = [
    '/vendor/bootstrap/bootstrap.min.css',
    '/vendor/bootstrap/bootstrap.bundle.min.js',
    '/vendor/fontawesome/css/all.min.css',
    '/vendor/jquery/jquery.min.js',
    '/vendor/animate/animate.min.css',
];

/**
 * Auto-update flag for offline songs (#132).
 * When true, the SW silently updates cached songs when changes are detected.
 * When false (default), the SW notifies the client and waits for confirmation.
 * Toggled via SET_AUTO_UPDATE message from the client.
 */
let autoUpdateOfflineSongs = false;

/**
 * In-flight navigation request map (#140).
 * Prevents duplicate fetches when rapid SPA navigation fires multiple
 * fetch events for the same URL concurrently. If a request for a URL
 * is already in-flight, subsequent requests share the same promise.
 * @type {Map<string, Promise<Response>>}
 */
const inflightNavigations = new Map();

/**
 * Send a message to all controlled clients.
 * @param {object} data Message payload
 */
async function notifyClients(data) {
    const clients = await self.clients.matchAll({ type: 'window' });
    clients.forEach(client => client.postMessage(data));
}

/* =========================================================================
 * INSTALL EVENT — Pre-cache essential assets
 * ========================================================================= */

self.addEventListener('install', (event) => {
    console.log('[SW] Installing service worker:', CACHE_VERSION);

    event.waitUntil(
        caches.open(CACHE_VERSION)
            .then(cache => {
                console.log('[SW] Pre-caching app shell assets');

                /* Local assets — must all succeed for install to complete */
                const localPromise = cache.addAll(PRECACHE_ASSETS);

                /*
                 * CDN assets — best effort. Failures are silently ignored so
                 * a CDN outage doesn't block service worker installation.
                 * These will be cached at runtime on the next page load anyway.
                 */
                const cdnPromise = Promise.allSettled(
                    PRECACHE_CDN_ASSETS.map(url =>
                        fetch(url, { mode: 'cors' })
                            .then(resp => {
                                if (resp.ok) return cache.put(url, resp);
                            })
                            .catch(() => console.warn('[SW] CDN precache skipped:', url))
                    )
                );

                /*
                 * Local vendor fallback files — best effort.
                 * These may not exist if the download-vendor script hasn't run.
                 */
                const vendorPromise = Promise.allSettled(
                    PRECACHE_VENDOR_ASSETS.map(path =>
                        fetch(path)
                            .then(resp => {
                                if (resp.ok) return cache.put(path, resp);
                            })
                            .catch(() => {})
                    )
                );

                /*
                 * Best-effort precache (#354) — the slim song index
                 * (WS-I #1017). Failures here MUST NOT block SW install
                 * (otherwise a flaky network at install-time prevents
                 * offline support forever). Cached opportunistically.
                 */
                const bestEffortPromise = Promise.allSettled(
                    PRECACHE_BEST_EFFORT_ASSETS.map(path =>
                        fetch(path)
                            .then(resp => {
                                if (resp.ok) return cache.put(path, resp);
                            })
                            .catch(() => console.warn('[SW] Best-effort precache skipped:', path))
                    )
                );

                /*
                 * Page fragments (#1597 RC3) — best effort, into their own
                 * versioned bucket.
                 *
                 * ELI5: grab the home screen and the songbook list up front so
                 * a freshly-installed app still works if you go offline before
                 * you have browsed anywhere.
                 *
                 * Detail: without this, a user who installs the PWA, downloads
                 * a songbook from Settings and then boards a plane has never
                 * fetched `/api?page=home` — so the shell loads and the first
                 * fragment request 503s. Failures here must not block install,
                 * same reasoning as the slim index above.
                 */
                const pagesPromise = caches.open(PAGES_CACHE).then(pagesCache =>
                    Promise.allSettled(
                        ['/api?page=home', '/api?page=songbooks'].map(path =>
                            fetch(path)
                                .then(resp => {
                                    if (resp.ok) return pagesCache.put(path, resp);
                                })
                                .catch(() => console.warn('[SW] Page precache skipped:', path))
                        )
                    )
                ).catch(() => { /* storage unavailable — nothing to do */ });

                return Promise.all([
                    localPromise, cdnPromise, vendorPromise, bestEffortPromise, pagesPromise,
                ]);
            })
            .then(() => {
                /*
                 * skipWaiting() policy (#354):
                 *
                 *   - FIRST install (no existing controller) → call
                 *     skipWaiting() immediately so the SW intercepts
                 *     the very first navigation. Without this, a user
                 *     who installs the PWA and reopens it offline
                 *     before any second navigation gets a "no SW + no
                 *     cached fallback" page-load failure.
                 *
                 *   - UPDATE (controller already exists) → stay in the
                 *     "waiting" state and let app.js show its
                 *     "New version available — Refresh" toast. This
                 *     preserves user agency over reloads mid-session
                 *     (no abrupt reload eating unsaved setlist edits)
                 *     while critical fixes still roll out fast on next
                 *     navigation or tab close.
                 *
                 * Detection: self.registration.active === null on
                 * first install, populated on updates.
                 */
                if (self.registration.active === null) {
                    console.log('[SW] First install; calling skipWaiting() to activate immediately');
                    return self.skipWaiting();
                }
                console.log('[SW] Update installed; awaiting user confirmation to activate');
            })
    );
});

/* =========================================================================
 * ACTIVATE EVENT — Clean up old caches
 * ========================================================================= */

/**
 * One-time rescue of downloads made BEFORE the #1597 RECENT/SAVED split.
 *
 * ELI5: songs you downloaded with the old app are sitting in the box that gets
 * tidied up. Move them into the safe box, once, so the fix doesn't arrive too
 * late to help you.
 *
 * Detail: pre-#1597, bulk downloads went into RECENT_CACHE alongside
 * incidental views, so simply shipping the split would leave every existing
 * download still exposed to the trim until the user happened to re-download.
 * We can tell the two apart exactly: the bulk handler has always stamped its
 * synthesised responses with `X-Bulk-Cached: true`, and the Cache API stores
 * response headers verbatim. Anything carrying that header was a deliberate
 * download; anything without it was a view.
 *
 * Guarded by a sentinel so the scan (up to RECENT_CACHE_LIMIT `match()` calls)
 * runs ONCE per device rather than on every deploy. Fully best-effort — a
 * failure here must never stop the SW activating.
 * https://developer.mozilla.org/en-US/docs/Web/API/Cache/put
 *
 * @returns {Promise<number>} How many entries were promoted
 */
async function swMigrateLegacyBulkDownloads() {
    let moved = 0;
    try {
        const saved = await caches.open(SAVED_CACHE);
        if (await saved.match(SAVED_SPLIT_SENTINEL)) return 0;

        const recent = await caches.open(RECENT_CACHE);
        for (const req of await recent.keys()) {
            const resp = await recent.match(req);
            if (!resp || resp.headers.get('X-Bulk-Cached') !== 'true') continue;
            await saved.put(req, resp.clone());
            await recent.delete(req);
            moved++;
        }

        await saved.put(SAVED_SPLIT_SENTINEL, new Response('', {
            status: 200,
            headers: { 'Content-Type': 'text/plain' },
        }));
        if (moved > 0) {
            console.log('[SW] Promoted', moved, 'legacy bulk-downloaded songs to', SAVED_CACHE);
        }
    } catch (error) {
        console.warn('[SW] Legacy download migration skipped:', error && error.message);
    }
    return moved;
}

self.addEventListener('activate', (event) => {
    console.log('[SW] Activating service worker:', CACHE_VERSION);

    event.waitUntil(
        caches.keys()
            .then(cacheNames => {
                /* Delete every bucket that isn't on the keep-list (#1597 RC2).
                   The keep-list lives in swKeptCacheNames() rather than being
                   inlined here, because when it WAS inlined it quietly omitted
                   the audio bucket and every deploy wiped users' downloaded
                   MP3s while the UI still showed the songbook as saved. */
                return Promise.all(
                    cacheNames
                        .filter(name => !swIsCacheKept(name))
                        .map(name => {
                            console.log('[SW] Deleting old cache:', name);
                            return caches.delete(name);
                        })
                );
            })
            .then(() => {
                /* Take control of all open tabs immediately. Done BEFORE the
                   migration below so control transfer is never delayed by a
                   one-time scan of up to 2000 cache entries. */
                return self.clients.claim();
            })
            .then(() => swMigrateLegacyBulkDownloads())
    );
});

/* =========================================================================
 * FETCH EVENT — Network-first strategy with offline fallback
 *
 * Strategy per resource type:
 *   1. Trusted CDNs  → Network-first, cache for offline (Bootstrap, FA, jQuery)
 *   2. Other CDNs    → Network-only (analytics, third-party scripts)
 *   3. API requests  → Network-first, cache song pages for offline (#105)
 *   4. Local assets  → Network-first, cache on success, serve cache if offline
 *   5. Navigation    → Network-first, fall back to cached '/' for offline shell
 * ========================================================================= */

self.addEventListener('fetch', (event) => {
    /* The Cache API only supports GET responses — `cache.put()` on a
     * HEAD / POST / PUT / DELETE / PATCH response throws
     *   TypeError: Failed to execute 'put' on 'Cache':
     *               Request method 'HEAD' is unsupported.
     * Every branch below assumes GET (network-first-with-cache, etc.),
     * so pass non-GET requests straight through to the network without
     * SW interception. The offline-indicator's HEAD probe to
     * /manifest.json (#354 B24, commit 6cfd3c6) is the specific
     * request that surfaced this; any future non-GET probe is now
     * also covered. Background Sync queueing for write requests is
     * handled by the separate 'sync' event handler below, not here. */
    if (event.request.method !== 'GET') return;

    const url = new URL(event.request.url);

    /* --- CDN / Third-party resources --- */
    if (url.origin !== self.location.origin) {
        /*
         * Trusted CDN resources (Bootstrap, Font Awesome, jQuery, etc.)
         * are cached with network-first strategy so the app shell renders
         * offline. These CDNs serve CORS headers, so cached responses
         * remain readable for SRI verification.
         */
        if (TRUSTED_CDN_ORIGINS.some(origin => url.origin === origin)) {
            event.respondWith(networkFirstWithCache(event.request));
            return;
        }
        /* Other third-party resources: let the browser handle normally */
        return;
    }

    /* --- Slim song index (WS-I #1017): network-first, cached to the
       CACHE_VERSION bucket so the OFFLINE browse/search fallback in
       search.js can read it. MUST precede the generic /api branch below,
       which returns a 503 for non-song-page API calls when offline rather
       than serving the cached index. networkFirstWithCache() refreshes the
       cached copy on every online fetch and serves it on network failure. */
    if (url.pathname === '/api' && url.searchParams.get('action') === 'songs_index') {
        event.respondWith(networkFirstWithCache(event.request));
        return;
    }

    /* --- API requests: network-first with cache for song pages (#105, #131)
           and for the navigable page fragments (#1597 RC3) --- */
    if (url.pathname.startsWith('/api')) {
        const isSongPage = url.searchParams.get('page') === 'song';
        const songId = url.searchParams.get('id');
        /* Non-null for home / songbooks / songbook / search — the fragments
           that make an offline download actually browsable. */
        const offlinePage = swOfflinePageFragment(event.request.url);
        /* `cache: 'no-store'` bypasses the browser HTTP cache so the
         * SW's network-first guarantee actually delivers a fresh
         * server response — see networkFirstWithCache() for the full
         * rationale. Otherwise `/api?...` calls could be intercepted
         * by the browser's HTTP cache before the SW sees the round-
         * trip, defeating the "online = fresh" contract. */
        event.respondWith(
            fetch(event.request, { cache: 'no-store' })
                .then(async (response) => {
                    /* Page fragments (#1597 RC3) — refresh the versioned
                       fragment bucket on every online fetch, then keep it
                       under its cap. Nothing here can reach the app shell in
                       CACHE_VERSION or the user's songs in SAVED_CACHE. */
                    if (offlinePage && response.ok) {
                        try {
                            const pages = await caches.open(PAGES_CACHE);
                            await pages.put(event.request, response.clone());
                            const doomed = swPagesKeysToTrim(await pages.keys(), PAGES_CACHE_LIMIT);
                            await Promise.all(doomed.map(k => pages.delete(k)));
                        } catch (error) {
                            /* Storage full / private mode — the page still
                               renders; only the offline copy is lost. */
                            console.warn('[SW] Page fragment cache skipped:', error && error.message);
                        }
                    }

                    /* Cache song page API responses for offline access.
                       #1597 RC1 — a song the user DELIBERATELY downloaded
                       lives in SAVED_CACHE, so update detection has to look
                       there first; otherwise a saved song would silently stop
                       receiving updates and would also get a duplicate copy
                       written into the recency bucket. */
                    if (isSongPage && response.ok) {
                        const saved = await caches.open(SAVED_CACHE);
                        const inSaved = await saved.match(event.request);
                        const cache = inSaved ? saved : await caches.open(RECENT_CACHE);
                        const existing = inSaved || await cache.match(event.request);

                        if (existing) {
                            /* Compare content to detect updates (#131) */
                            const [newBody, oldBody] = await Promise.all([
                                response.clone().text(),
                                existing.text(),
                            ]);

                            if (newBody !== oldBody) {
                                if (autoUpdateOfflineSongs) {
                                    /* Auto-update: silently cache the new version */
                                    await cache.put(event.request, response.clone());
                                    notifyClients({
                                        type: 'SONG_UPDATED',
                                        songId,
                                        auto: true,
                                    });
                                } else {
                                    /* Manual mode: notify user, don't overwrite yet */
                                    notifyClients({
                                        type: 'SONG_UPDATE_AVAILABLE',
                                        songId,
                                        url: event.request.url,
                                    });
                                }
                            }
                            /* If content unchanged, refresh the cache timestamp */
                            else {
                                await cache.put(event.request, response.clone());
                            }
                        } else {
                            /* Not previously cached — just cache it */
                            await cache.put(event.request, response.clone());
                        }
                    }
                    return response;
                })
                .catch(() => {
                    /* Offline: serve the cached copy for anything we cache.
                       `caches.match()` with no `cacheName` searches EVERY
                       bucket, so this finds a song in SAVED_CACHE or
                       RECENT_CACHE and a fragment in PAGES_CACHE without the
                       SW having to guess which one it landed in.
                       https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/match

                       #1597 RC3 — `offlinePage` is what stops home / songbooks
                       / songbook / search falling through to the 503 below and
                       rendering the red "Failed to load page" card, which is
                       what made even a complete download unbrowsable. */
                    if (isSongPage || offlinePage) {
                        return caches.match(event.request).then(cached => {
                            if (cached) return cached;
                            return new Response(
                                JSON.stringify({ error: 'You appear to be offline.' }),
                                { status: 503, headers: { 'Content-Type': 'application/json' } }
                            );
                        });
                    }
                    return new Response(
                        JSON.stringify({ error: 'You appear to be offline. Please check your connection.' }),
                        { status: 503, headers: { 'Content-Type': 'application/json' } }
                    );
                })
        );
        return;
    }

    /* (The whole-corpus songs_json branch was removed in WS-I #1017 — it was
       unreachable anyway, since the generic /api branch above catches it
       first, and nothing on the client requests the corpus any more. The
       slim index has its own branch ahead of the generic /api one.) */

    /* --- Navigation requests: network-first, offline shell fallback --- */
    /* Deduplicates concurrent fetches for the same URL (#140) */
    if (event.request.mode === 'navigate') {
        const navKey = url.pathname + url.search;
        const inflight = inflightNavigations.get(navKey);

        if (inflight) {
            /* Another fetch for this URL is already in-flight — share it */
            event.respondWith(inflight.then(r => r.clone()));
            return;
        }

        /* `cache: 'no-store'` bypasses the browser HTTP cache so a
         * navigation to /songbooks/, /song/<id>, /tag/<slug> etc.
         * always reaches the origin when online. Without this, a
         * server response with `Cache-Control: max-age=N` (or no
         * cache headers at all — browsers heuristic-cache HTML for
         * up to ~10 % of the response's age) could be served from
         * the browser's HTTP cache without the SW seeing fresh
         * content. The SW's CACHE_VERSION bucket remains the offline
         * fallback. */
        const navigationPromise = fetch(event.request, { cache: 'no-store' })
            .then(response => {
                /* Only cache successful (2xx) responses — never cache
                 * redirects (301/302) as that causes infinite redirect
                 * loops when served from cache (#140) */
                if (response.ok) {
                    const clone = response.clone();
                    caches.open(CACHE_VERSION).then(cache => {
                        cache.put(event.request, clone);
                    });
                }
                return response;
            })
            .catch(() => {
                /* Offline — serve cached version, app shell, or branded fallback */
                return caches.match(event.request)
                    .then(cached => cached || caches.match('/'))
                    .then(resp => resp || offlineFallbackResponse());
            })
            .finally(() => {
                inflightNavigations.delete(navKey);
            });

        inflightNavigations.set(navKey, navigationPromise);
        event.respondWith(navigationPromise.then(r => r.clone()));
        return;
    }

    /* --- Audio / sheet-music: cache-first (#401) ---
       On-demand caching: once a user plays or views a song, the underlying
       audio or PDF is cached. Subsequent plays — including offline — hit
       the cache immediately with no network round-trip. Separate cache
       bucket so it can be cleared independently of the app shell.

       #1358 — also match the gated /audio/<id>.mp3 route so SIGNED audio
       URLs cache like the rest. NOTE: a signed URL carries ?exp=…&sig=… and
       EXPIRES, so a precached gated mp3 is BEST-EFFORT offline — a fresh
       navigation re-mints the URL (new query string = new cache key), and an
       expired link served from cache will 403 on a cache-miss refetch. PD /
       un-gated audio (emitted as the legacy /data/audio/… literal while
       signing is off) is unaffected — it has no query string and caches
       permanently as before. */
    if (event.request.method === 'GET'
        && (url.pathname.startsWith('/data/audio/')
            || url.pathname.startsWith('/data/music/')
            || url.pathname.startsWith('/audio/'))) {
        event.respondWith(
            caches.open(MEDIA_CACHE).then(async (cache) => {
                const hit = await cache.match(event.request);
                if (hit) return hit;
                try {
                    const res = await fetch(event.request);
                    if (res.ok) cache.put(event.request, res.clone());
                    return res;
                } catch {
                    /* Offline + not cached — let the media element show its
                       own error UI rather than injecting a PNG/JSON. */
                    return new Response('', { status: 504, statusText: 'Offline' });
                }
            })
        );
        return;
    }

    /* --- All other local assets: network-first with cache fallback --- */
    event.respondWith(networkFirstWithCache(event.request));
});

/* =========================================================================
 * HELPER FUNCTIONS
 * ========================================================================= */

/**
 * Self-contained offline fallback page.
 * Shown when the user is offline AND no cached version of the page exists
 * (e.g., first launch of a freshly installed PWA with no network).
 * All styles and assets are inlined so no external requests are needed.
 */
const OFFLINE_FALLBACK_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
<title>iHymns — Offline</title>
<script>(function(){try{var t=(window.localStorage&&localStorage.getItem('ihymns_theme'))||'system';var bs='light',it=t;if(t==='system'){var d=window.matchMedia&&matchMedia('(prefers-color-scheme: dark)').matches;it=d?'dark':'light';bs=it;}else if(t==='dark'){bs='dark';}else if(t==='high-contrast'){bs='light';}var h=document.documentElement;h.setAttribute('data-bs-theme',bs);h.setAttribute('data-ihymns-theme',it);if(it==='high-contrast')h.setAttribute('data-ihymns-contrast','high');var c=localStorage.getItem('ihymns_cvd_mode');if(c)h.setAttribute('data-ihymns-cvd',c);}catch(e){}})();</script>
<style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{
  --accent:#6366f1;--accent-end:#8b5cf6;
  --bg:#f8fafc;--card:#fff;--text:#1e293b;--text-sec:#64748b;--text-muted:#94a3b8;
  --radius:16px;--shadow:0 4px 24px rgba(0,0,0,.08);
}
@media(prefers-color-scheme:dark){:root{
  --accent:#818cf8;--accent-end:#a78bfa;
  --bg:#0f172a;--card:#1e293b;--text:#f1f5f9;--text-sec:#94a3b8;--text-muted:#64748b;
  --shadow:0 4px 24px rgba(0,0,0,.3);
}}
/* Explicit user theme (set by the inline script above from localStorage) wins
   over the OS @media fallback so a manual light/dark/high-contrast choice is
   honoured offline too. */
[data-bs-theme="light"]{--accent:#6366f1;--accent-end:#8b5cf6;--bg:#f8fafc;--card:#fff;--text:#1e293b;--text-sec:#64748b;--text-muted:#94a3b8;--shadow:0 4px 24px rgba(0,0,0,.08)}
[data-bs-theme="dark"]{--accent:#818cf8;--accent-end:#a78bfa;--bg:#0f172a;--card:#1e293b;--text:#f1f5f9;--text-sec:#94a3b8;--text-muted:#64748b;--shadow:0 4px 24px rgba(0,0,0,.3)}
[data-ihymns-theme="high-contrast"]{--accent:#0000cc;--accent-end:#0000cc;--bg:#fff;--card:#fff;--text:#000;--text-sec:#333;--text-muted:#555;--shadow:none}
html,body{height:100%;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;
  -webkit-font-smoothing:antialiased;background:var(--bg);color:var(--text)}
body{display:flex;align-items:center;justify-content:center;padding:24px;
  padding-top:env(safe-area-inset-top,0);padding-bottom:env(safe-area-inset-bottom,0)}
.offline-wrap{text-align:center;max-width:420px;width:100%}
.offline-icon{margin:0 auto 28px;width:88px;height:88px;border-radius:50%;
  background:linear-gradient(135deg,var(--accent),var(--accent-end));
  display:flex;align-items:center;justify-content:center;
  box-shadow:0 8px 32px rgba(99,102,241,.25);animation:pulse-glow 3s ease-in-out infinite}
.offline-icon svg{width:44px;height:44px;opacity:.95}
@keyframes pulse-glow{0%,100%{box-shadow:0 8px 32px rgba(99,102,241,.25)}
  50%{box-shadow:0 8px 48px rgba(99,102,241,.4)}}
.offline-card{background:var(--card);border-radius:var(--radius);padding:32px 28px;
  box-shadow:var(--shadow)}
h1{font-size:1.5rem;font-weight:700;margin-bottom:8px;color:var(--accent);
  background:linear-gradient(135deg,var(--accent),var(--accent-end));
  -webkit-background-clip:text;-webkit-text-fill-color:transparent;
  background-clip:text}
[data-ihymns-theme="high-contrast"] h1{background:none;-webkit-text-fill-color:currentColor}
.subtitle{font-size:.95rem;color:var(--text-sec);margin-bottom:24px;line-height:1.5}
.divider{width:48px;height:3px;border-radius:2px;margin:0 auto 24px;
  background:linear-gradient(90deg,var(--accent),var(--accent-end))}
.help-text{font-size:.875rem;color:var(--text-muted);line-height:1.6;margin-bottom:24px}
.help-text p{margin-bottom:12px}
.retry-btn{display:inline-flex;align-items:center;gap:8px;padding:12px 28px;
  border:none;border-radius:50px;font-size:.95rem;font-weight:600;cursor:pointer;
  background:linear-gradient(135deg,var(--accent),var(--accent-end));color:#fff;
  box-shadow:0 4px 16px rgba(99,102,241,.3);transition:transform .15s ease,box-shadow .15s ease}
.retry-btn:hover{transform:translateY(-1px);box-shadow:0 6px 24px rgba(99,102,241,.4)}
.retry-btn:active{transform:translateY(0);box-shadow:0 2px 8px rgba(99,102,241,.3)}
.retry-icon{display:inline-block;width:18px;height:18px;transition:transform .3s ease}
.retry-btn:hover .retry-icon{transform:rotate(180deg)}
.brand{margin-top:28px;font-size:.8rem;color:var(--text-muted);letter-spacing:.02em}
@media(prefers-reduced-motion:reduce){
  .offline-icon{animation:none}
  .retry-icon{transition:none}
}
</style>
</head>
<body>
<div class="offline-wrap">
  <div class="offline-icon">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"
         stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <line x1="1" y1="1" x2="23" y2="23"/>
      <path d="M16.72 11.06A10.94 10.94 0 0 1 19 12.55"/>
      <path d="M5 12.55a10.94 10.94 0 0 1 5.17-2.39"/>
      <path d="M10.71 5.05A16 16 0 0 1 22.56 9"/>
      <path d="M1.42 9a15.91 15.91 0 0 1 4.7-2.88"/>
      <path d="M8.53 16.11a6 6 0 0 1 6.95 0"/>
      <line x1="12" y1="20" x2="12.01" y2="20"/>
    </svg>
  </div>
  <div class="offline-card">
    <h1>You're Offline</h1>
    <p class="subtitle">iHymns needs an internet connection to load for the first time.</p>
    <div class="divider"></div>
    <div class="help-text">
      <p>Once you've opened iHymns with a connection, it will cache everything you need for offline use.</p>
      <p>You can also download entire songbooks for offline access from Settings.</p>
    </div>
    <button class="retry-btn" onclick="window.location.reload()">
      <svg class="retry-icon" viewBox="0 0 24 24" fill="none"
           stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
        <polyline points="23 4 23 10 17 10"/>
        <path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10"/>
      </svg>
      Try Again
    </button>
  </div>
  <p class="brand">iHymns — Christian Hymns &amp; Worship Songs</p>
</div>
</body>
</html>`;

/**
 * Return the offline fallback page as a Response.
 * @returns {Response}
 */
function offlineFallbackResponse() {
    return new Response(OFFLINE_FALLBACK_HTML, {
        status: 503,
        statusText: 'Service Unavailable',
        headers: { 'Content-Type': 'text/html; charset=UTF-8' }
    });
}

/**
 * Network-first caching strategy.
 * Tries the network first; on success, caches the response.
 * On failure (offline), serves from cache if available.
 *
 * @param {Request} request The fetch request
 * @returns {Promise<Response>} The response
 */
async function networkFirstWithCache(request) {
    try {
        /* Try network first.
         *
         * `cache: 'no-store'` bypasses the BROWSER'S HTTP cache so the
         * SW's "network-first" promise actually delivers a fresh
         * server response — without it, the browser's own HTTP cache
         * can intercept the request first (per Cache-Control headers
         * the PHP response sends, or defaults like
         * `max-age` from absent headers), and the SW gets handed a
         * stale response that LOOKS fresh. That's the layered-cache
         * trap that surfaced on dev.ihymns.app this session — even
         * after unregistering the SW, curators still saw stale
         * `/songbooks/` because the browser HTTP cache kept serving
         * the old HTML. With `no-store`, the SW always round-trips
         * to the origin when online; the SW's own cache (CACHE_VERSION
         * bucket) remains the single source of offline truth. */
        const networkResponse = await fetch(request, { cache: 'no-store' });

        /* Cache the successful response */
        if (networkResponse.ok) {
            const cache = await caches.open(CACHE_VERSION);
            cache.put(request, networkResponse.clone());
        }

        return networkResponse;

    } catch (error) {
        /* Network failed — try cache */
        const cachedResponse = await caches.match(request);
        if (cachedResponse) {
            return cachedResponse;
        }

        /* Nothing in cache either — show the branded offline page */
        return offlineFallbackResponse();
    }
}

/* =========================================================================
 * MESSAGE EVENT — Handle SKIP_WAITING from the client (#83)
 *
 * When the user clicks the "Refresh" button in the update notification,
 * the client sends a { type: 'SKIP_WAITING' } message. This tells the
 * waiting service worker to activate immediately, replacing the old one.
 * The client then receives a 'controllerchange' event and reloads.
 * ========================================================================= */

/* =========================================================================
 * BACKGROUND SYNC — offline queue drain (#337, #338)
 *
 * `js/modules/offline-queue.js` registers a Sync tag of the form
 * `ihymns-queue-<type>` whenever the user performs an action while
 * offline (song-request submission, favourite toggle, setlist save).
 * The OS then wakes this SW up on reconnect and dispatches a `sync`
 * event carrying that tag.
 *
 * We don't replay the HTTP request from inside the SW (the payload
 * needs session cookies + may need CSRF tokens that the queue doesn't
 * carry). Instead, we echo a `QUEUE_DRAIN` message to every open
 * client; the page's drain handler owns the real POST. If no client
 * is open, the drain happens next time a page loads via the
 * `navigator.onLine` fallback in offline-queue.js.
 * ========================================================================= */
self.addEventListener('sync', (event) => {
    if (!event.tag || !event.tag.startsWith('ihymns-queue-')) return;
    event.waitUntil((async () => {
        const clients = await self.clients.matchAll({
            includeUncontrolled: true,
            type: 'window',
        });
        for (const c of clients) {
            c.postMessage({ type: 'QUEUE_DRAIN', tag: event.tag });
        }
    })());
});

self.addEventListener('message', (event) => {
    if (!event.data) return;

    if (event.data.type === 'SKIP_WAITING') {
        console.log('[SW] Received SKIP_WAITING — activating now');
        self.skipWaiting();
    }

    /*
     * Download songs for offline use via bulk API (#359 rewrite).
     *
     * Instead of fetching each song individually (3,612 requests!),
     * we fetch entire songbooks in bulk via /api?action=bulk_songs.
     * Each bulk response contains all rendered HTML for a songbook,
     * which we split into individual cache entries. This reduces
     * thousands of requests to ~6, making the download near-instant
     * on any decent connection.
     *
     * Message format:
     *   { type: 'CACHE_ALL_SONGS', songbooks: ['CP','JP',...] }
     *   OR legacy: { type: 'CACHE_ALL_SONGS', songIds: [...] }
     */
    if (event.data.type === 'CACHE_ALL_SONGS') {
        const songbooks = event.data.songbooks;
        const totalSongs = event.data.totalSongs || 0;

        /* Legacy fallback: if songIds array sent, use old per-song method */
        if (!songbooks && Array.isArray(event.data.songIds)) {
            _downloadSongsLegacy(event.data.songIds);
            return;
        }

        if (!Array.isArray(songbooks) || songbooks.length === 0) return;

        /* Self-invoking async wrapper so a rejection from caches.open(),
           fetch() or cache.put() surfaces as a progress message with an
           error string rather than silently stalling the UI at
           "Downloading <book>…" indefinitely (#452). */
        (async () => {
            let completed = 0;
            let failed = 0;
            const total = totalSongs;

            try {
                /* #1597 RC1 — a bulk download is the definition of a
                   deliberate save, so it goes into SAVED_CACHE, which nothing
                   in this SW ever trims. Before the split it went into the
                   capped recency bucket and the next single song view deleted
                   the overflow. */
                const cache = await caches.open(SAVED_CACHE);

                for (const songbook of songbooks) {
                    notifyClients({
                        type: 'CACHE_ALL_SONGS_PROGRESS',
                        completed, failed, total,
                        status: `Downloading ${songbook}...`,
                    });

                    try {
                        const resp = await fetch(`/api?action=bulk_songs&songbook=${encodeURIComponent(songbook)}`);
                        if (!resp.ok) {
                            failed++;
                            notifyClients({
                                type: 'CACHE_ALL_SONGS_PROGRESS',
                                completed, failed, total,
                                warning: `Skipped ${songbook}: HTTP ${resp.status}`,
                            });
                            continue;
                        }

                        const data = await resp.json();
                        const songs = data.songs || {};
                        const ids = Object.keys(songs);

                        for (const id of ids) {
                            try {
                                const url = `/api?page=song&id=${encodeURIComponent(id)}`;
                                const html = songs[id];
                                const fakeResponse = new Response(html, {
                                    status: 200,
                                    headers: {
                                        'Content-Type': 'text/html; charset=UTF-8',
                                        'X-Bulk-Cached': 'true',
                                    },
                                });
                                await cache.put(url, fakeResponse);
                                completed++;
                            } catch (e) {
                                failed++;
                            }
                        }

                        /* Drop this songbook's entries from the recency bucket
                           now that SAVED_CACHE holds a fresh copy of the whole
                           book (#1597 RC1).
                           WHY IT MATTERS: `caches.match()` searches buckets in
                           CREATION order and returns the FIRST hit, and
                           RECENT_CACHE predates SAVED_CACHE on any upgraded
                           device — so a leftover recency copy would SHADOW the
                           download the user just made and serve them staler
                           HTML offline. One keys() scan per songbook rather
                           than a delete() per song. */
                        try {
                            const recent = await caches.open(RECENT_CACHE);
                            const book = songbook.toUpperCase();
                            for (const req of await recent.keys()) {
                                if (swSongbookFromSongCacheUrl(req.url) === book) {
                                    await recent.delete(req);
                                }
                            }
                        } catch (e) {
                            /* Non-fatal: worst case a duplicate lingers. */
                        }
                    } catch (e) {
                        /* Network error for this songbook — surface it so
                           the UI moves on rather than hanging silently. */
                        failed++;
                        notifyClients({
                            type: 'CACHE_ALL_SONGS_PROGRESS',
                            completed, failed, total,
                            warning: `Network error on ${songbook}: ${e && e.message ? e.message : 'unknown'}`,
                        });
                    }

                    notifyClients({
                        type: 'CACHE_ALL_SONGS_PROGRESS',
                        completed, failed, total,
                    });
                }
            } catch (e) {
                /* caches.open() failed (storage quota, private-mode,
                   Safari ITP etc.) — let the UI know instead of
                   pretending to be mid-download forever. */
                notifyClients({
                    type: 'CACHE_ALL_SONGS_PROGRESS',
                    completed, failed, total,
                    error: (e && e.message) ? e.message : 'Cache unavailable',
                    /* #1597 RC5 — `done` is what releases the client's
                       progress bar. Without it this branch left the bar
                       spinning at whatever percentage it had reached, forever,
                       because settings.js only completed on
                       completed + failed >= total. */
                    done: true,
                });
                return;
            }

            /* Final report */
            notifyClients({
                type: 'CACHE_ALL_SONGS_PROGRESS',
                completed, failed, total,
                done: true,
            });
        })();
    }

    /* Legacy per-song download (fallback if bulk not available) */
    async function _downloadSongsLegacy(songIds) {
        const total = songIds.length;
        let completed = 0, failed = 0;
        /* Deliberate download → the untrimmed bucket, same as the bulk path
           above (#1597 RC1). */
        const cache = await caches.open(SAVED_CACHE);
        const BATCH = 20;
        for (let i = 0; i < songIds.length; i += BATCH) {
            const batch = songIds.slice(i, i + BATCH);
            await Promise.allSettled(batch.map(async (id) => {
                try {
                    const url = `/api?page=song&id=${encodeURIComponent(id)}`;
                    const r = await fetch(url);
                    if (r.ok) { await cache.put(url, r); completed++; } else { failed++; }
                } catch { failed++; }
            }));
            notifyClients({ type: 'CACHE_ALL_SONGS_PROGRESS', completed, failed, total });
        }
        /* Terminal message carries `done` so the client releases its progress
           bar even if some songs failed (#1597 RC5). */
        notifyClients({ type: 'CACHE_ALL_SONGS_PROGRESS', completed, failed, total, done: true });
    }

    /* Set auto-update preference (#132) */
    if (event.data.type === 'SET_AUTO_UPDATE') {
        autoUpdateOfflineSongs = !!event.data.enabled;
        console.log('[SW] Auto-update offline songs:', autoUpdateOfflineSongs);
    }

    /* Accept a pending song update — cache the fresh version (#131) */
    if (event.data.type === 'UPDATE_SONG_CACHE' && event.data.url) {
        try {
            const cacheUrl = new URL(event.data.url, self.location.origin);
            if (cacheUrl.origin !== self.location.origin) return;
        } catch { return; }

        (async () => {
            try {
                /* Refresh the copy IN PLACE — a song the user downloaded must
                   stay in SAVED_CACHE after an update, or accepting an update
                   would quietly demote it back into the trimmable recency
                   bucket and re-create #1597 RC1 one song at a time. */
                const saved = await caches.open(SAVED_CACHE);
                const cache = (await saved.match(event.data.url))
                    ? saved
                    : await caches.open(RECENT_CACHE);
                const response = await fetch(event.data.url);
                if (response.ok) {
                    await cache.put(event.data.url, response);
                    notifyClients({
                        type: 'SONG_UPDATED',
                        songId: event.data.songId,
                        auto: false,
                    });
                }
            } catch (error) {
                console.warn('[SW] Failed to update cached song:', error.message);
            }
        })();
    }

    /* Pre-cache a batch of audio URLs into MEDIA_CACHE (#401).
     * Settings page sends this when the "Include audio in offline
     * downloads" toggle is on — once per songbook covered by the
     * current download, after CACHE_ALL_SONGS has been dispatched.
     * Message: { type: 'CACHE_AUDIO_URLS', urls: [...], songbook: 'XX' }
     */
    if (event.data.type === 'CACHE_AUDIO_URLS' && Array.isArray(event.data.urls)) {
        const urls = event.data.urls;
        const songbook = event.data.songbook || '';

        caches.open(MEDIA_CACHE).then(async (cache) => {
            let completed = 0, failed = 0;
            const total = urls.length;
            const BATCH = 6;

            for (let i = 0; i < urls.length; i += BATCH) {
                const batch = urls.slice(i, i + BATCH);
                await Promise.allSettled(batch.map(async (u) => {
                    try {
                        const cacheUrl = new URL(u, self.location.origin);
                        if (cacheUrl.origin !== self.location.origin) { failed++; return; }
                        const existing = await cache.match(u);
                        if (existing) { completed++; return; }
                        const r = await fetch(u);
                        if (r.ok) { await cache.put(u, r); completed++; }
                        else { failed++; }
                    } catch { failed++; }
                }));
                notifyClients({
                    type: 'CACHE_AUDIO_PROGRESS',
                    songbook, completed, failed, total,
                });
            }
            notifyClients({
                type: 'CACHE_AUDIO_PROGRESS',
                songbook, completed, failed, total, done: true,
            });
        });
    }

    /* Evict every cached entry belonging to one songbook (#401, #1597 RC4).
     * Removes matching entries from BOTH song buckets (RECENT_CACHE and
     * SAVED_CACHE — a "Remove from offline" that left the deliberate download
     * behind would be a lie) and from MEDIA_CACHE.
     *
     * #1597 RC4 — the media sweep previously matched
     * `/data/audio/<songbook>/` SUBDIRECTORIES, a layout this app has never
     * emitted; the real URLs are flat `/data/audio/<SongId>.mp3`. So it
     * matched nothing, removed nothing, and reported success. Both sweeps now
     * go through the shared `swSongbookFrom*Url()` helpers, which are what
     * `tests/test-offline-cache-policy.js` pins.
     * Message: { type: 'EVICT_SONGBOOK', songbook: 'XX' }
     */
    if (event.data.type === 'EVICT_SONGBOOK' && typeof event.data.songbook === 'string') {
        const songbook = event.data.songbook;
        if (!/^[A-Za-z0-9_-]{1,16}$/.test(songbook)) return;
        const book = songbook.toUpperCase();
        (async () => {
            let removed = 0;
            for (const cacheName of [RECENT_CACHE, SAVED_CACHE]) {
                try {
                    const songs = await caches.open(cacheName);
                    for (const req of await songs.keys()) {
                        if (swSongbookFromSongCacheUrl(req.url) === book) {
                            if (await songs.delete(req)) removed++;
                        }
                    }
                } catch {}
            }
            try {
                const media = await caches.open(MEDIA_CACHE);
                for (const req of await media.keys()) {
                    if (swSongbookFromMediaUrl(req.url) === book) {
                        if (await media.delete(req)) removed++;
                    }
                }
            } catch {}
            notifyClients({ type: 'SONGBOOK_EVICTED', songbook, removed });
        })();
    }

    /* Report total bytes cached per songbook across both caches (#401).
     * Returns { type: 'CACHE_SIZES', sizes: { 'CP': 1234567, ... } } to the
     * requesting client. Sizes are summed from Content-Length headers (when
     * present) plus a per-entry fallback estimate for entries without them.
     * Message: { type: 'GET_CACHE_SIZES' }
     */
    if (event.data.type === 'GET_CACHE_SIZES') {
        const client = event.source;
        (async () => {
            const sizes = {};
            const addFor = (songbook, bytes) => {
                sizes[songbook] = (sizes[songbook] || 0) + bytes;
            };
            /* Both song buckets — a download in SAVED_CACHE is exactly the
               thing the user wants a size for (#1597 RC1). */
            for (const cacheName of [RECENT_CACHE, SAVED_CACHE]) {
                try {
                    const songs = await caches.open(cacheName);
                    for (const req of await songs.keys()) {
                        const songbook = swSongbookFromSongCacheUrl(req.url);
                        if (!songbook) continue;   /* incl. the migration sentinel */
                        const resp = await songs.match(req);
                        const len = Number(resp?.headers.get('content-length')) || 4096;
                        addFor(songbook, len);
                    }
                } catch {}
            }
            try {
                /* #1597 RC4 — the flat `/data/audio/<SongId>.mp3` shape the
                   app actually emits. The old subdirectory regex matched no
                   real URL, so every songbook's audio counted as 0 bytes. */
                const media = await caches.open(MEDIA_CACHE);
                for (const req of await media.keys()) {
                    const songbook = swSongbookFromMediaUrl(req.url);
                    if (!songbook) continue;
                    const resp = await media.match(req);
                    const len = Number(resp?.headers.get('content-length')) || 262144;
                    addFor(songbook, len);
                }
            } catch {}
            client?.postMessage({ type: 'CACHE_SIZES', sizes });
        })();
    }

    /* Cache a song page (#105, #1597 RC1).
     *
     * TWO CALLERS, TWO INTENTS:
     *   - router.js posts this on EVERY song view with no `saved` flag. That
     *     is a recency hint: it lands in the capped RECENT_CACHE and the trim
     *     below applies.
     *   - the Download buttons (offline-ui.js, settings.js) post
     *     `saved: true`. That is a promise: it lands in SAVED_CACHE, which
     *     NOTHING here trims.
     *
     * Conflating the two is what made a 3,517-song download evaporate the
     * moment its owner opened a single song. The flag defaults to falsy, so
     * router.js keeps its existing behaviour unchanged.
     */
    if (event.data.type === 'CACHE_SONG' && event.data.url) {
        /* Validate URL origin to prevent cache poisoning */
        try {
            const cacheUrl = new URL(event.data.url, self.location.origin);
            if (cacheUrl.origin !== self.location.origin) return;
        } catch { return; }

        const isDeliberate = event.data.saved === true;
        const targetName = swSongCacheName(isDeliberate);

        caches.open(targetName).then(async (cache) => {
            try {
                const response = await fetch(event.data.url);
                if (!response.ok) return;
                await cache.put(event.data.url, response);

                if (isDeliberate) {
                    /* Drop any recency duplicate so the untrimmed copy is the
                       one `caches.match()` finds. See the bulk path above for
                       why creation order makes this matter. */
                    try {
                        const recent = await caches.open(RECENT_CACHE);
                        await recent.delete(event.data.url);
                    } catch { /* non-fatal */ }
                    /* NO TRIM. This bucket shrinks only on an explicit
                       EVICT_SONGBOOK from the user. */
                    return;
                }

                /* Recency bucket only: evict the oldest entries over the cap. */
                const doomed = swKeysToTrim(await cache.keys(), RECENT_CACHE_LIMIT);
                await Promise.all(doomed.map(k => cache.delete(k)));
            } catch (error) {
                console.warn('[SW] Failed to cache song:', event.data.url, error.message);
            }
        });
    }
});
