<?php
/**
 * Service Worker PHP Wrapper (#81)
 *
 * This file is served as JavaScript but generated by PHP so that
 * the cache version is automatically derived from infoAppVer.php.
 * The .htaccess rule rewrites /service-worker.js → service-worker.js.php.
 *
 * Content-Type is set to JavaScript so the browser treats it correctly.
 */
header('Content-Type: application/javascript; charset=UTF-8');
header('Cache-Control: no-cache, no-store, must-revalidate');
header('Service-Worker-Allowed: /');

require_once __DIR__ . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'infoAppVer.php';
require_once __DIR__ . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'config.php';
$swVersion = $app['Application']['Version']['Number'] ?? '0.0.0';
$libs = APP_CONFIG['libraries'];

/* Collect CDN URLs for critical app shell resources */
$cdnAssets = array_filter([
    $libs['bootstrap']['css_cdn']   ?? null,
    $libs['bootstrap']['js_cdn']    ?? null,
    $libs['fontawesome']['css_cdn'] ?? null,
    $libs['jquery']['js_cdn']       ?? null,
    $libs['animatecss']['css_cdn']  ?? null,
]);

/* Collect local vendor fallback paths */
$vendorAssets = array_filter([
    $libs['bootstrap']['css_local']   ?? null,
    $libs['bootstrap']['js_local']    ?? null,
    $libs['fontawesome']['css_local'] ?? null,
    $libs['jquery']['js_local']       ?? null,
    $libs['animatecss']['css_local']  ?? null,
]);
?>
/**
 * iHymns — Service Worker
 *
 * Copyright (c) 2026 iHymns. All rights reserved.
 *
 * PURPOSE:
 * Provides offline support and caching for the iHymns PWA.
 *
 * STRATEGY:
 * "Network-first with offline fallback" — as per requirements:
 *   - Always try to load content from the host (network) first
 *   - Only fall back to cached content when the network is unreachable
 *   - Pre-caches essential app shell assets for instant offline access
 *   - Trusted CDN resources (Bootstrap, Font Awesome, jQuery, etc.) are
 *     cached for offline use — these CDNs serve CORS headers so SRI still works
 *
 * CACHE MANAGEMENT:
 *   - Cache version is derived from infoAppVer.php automatically
 *   - Old caches are automatically cleaned up on activation
 *
 * NOTE: This file is generated by PHP (service-worker.js.php) and served
 * via .htaccess rewrite as /service-worker.js. The PHP wrapper injects
 * the current app version into the CACHE_VERSION constant so it always
 * stays in sync with infoAppVer.php (#81).
 */

/* =========================================================================
 * CACHE CONFIGURATION
 * ========================================================================= */

/**
 * Cache version — derived from the application version in infoAppVer.php.
 * When the version is bumped by CI/CD, the service worker automatically
 * gets a new cache key, triggering a full cache purge on next load.
 */
const CACHE_VERSION = 'ihymns-v<?= $swVersion ?>';

/**
 * Songs cache (#105).
 * Separate bucket so it survives app version cache purges.
 * Stores recently viewed songs and bulk-downloaded songs for offline use.
 */
const RECENT_CACHE = 'ihymns-recent-songs';
const RECENT_CACHE_LIMIT = 2000;

/**
 * Assets to pre-cache during service worker installation.
 * These are the essential app shell files needed for offline access.
 */
const PRECACHE_ASSETS = [
    '/',
    '/css/app.css',
    '/css/accessibility.css',
    '/css/print.css',
    '/js/app.js',
    '/js/modules/router.js',
    '/js/modules/transitions.js',
    '/js/modules/settings.js',
    '/js/modules/search.js',
    '/js/modules/favorites.js',
    '/js/modules/pwa.js',
    '/js/modules/shuffle.js',
    '/js/modules/numpad.js',
    '/js/modules/share.js',
    '/js/modules/compare.js',
    '/js/modules/shortcuts.js',
    '/js/modules/request.js',
    '/js/modules/transpose.js',
    '/js/modules/reading-progress.js',
    '/js/modules/songbook-index.js',
    '/js/modules/search-history.js',
    '/js/modules/song-of-the-day.js',
    '/js/modules/offline-indicator.js',
    '/js/modules/storage-bridge.js',
    '/js/modules/subdomain-sync.js',
    '/manifest.json',
    '/assets/favicon.svg',
];

/**
 * Trusted CDN origins whose resources are cached for offline use.
 * These CDNs serve CORS headers (Access-Control-Allow-Origin: *)
 * so responses can be cached and later served with SRI verification.
 */
const TRUSTED_CDN_ORIGINS = [
    'https://cdn.jsdelivr.net',
    'https://cdnjs.cloudflare.com',
];

/**
 * Critical CDN assets to pre-cache during install for offline app shell.
 * Injected from config.php so CDN URLs stay in sync automatically.
 * These are fetched best-effort — CDN failures won't block installation.
 */
const PRECACHE_CDN_ASSETS = <?= json_encode(array_values($cdnAssets), JSON_UNESCAPED_SLASHES) ?>;

/**
 * Local vendor fallback paths — pre-cached best-effort.
 * These files are served when CDN resources are unavailable and the
 * CDN cache is also empty (e.g., first offline launch after install).
 */
const PRECACHE_VENDOR_ASSETS = <?= json_encode(
    array_map(fn($p) => '/' . $p, array_values($vendorAssets)),
    JSON_UNESCAPED_SLASHES
) ?>;

/**
 * Auto-update flag for offline songs (#132).
 * When true, the SW silently updates cached songs when changes are detected.
 * When false (default), the SW notifies the client and waits for confirmation.
 * Toggled via SET_AUTO_UPDATE message from the client.
 */
let autoUpdateOfflineSongs = false;

/**
 * In-flight navigation request map (#140).
 * Prevents duplicate fetches when rapid SPA navigation fires multiple
 * fetch events for the same URL concurrently. If a request for a URL
 * is already in-flight, subsequent requests share the same promise.
 * @type {Map<string, Promise<Response>>}
 */
const inflightNavigations = new Map();

/**
 * Send a message to all controlled clients.
 * @param {object} data Message payload
 */
async function notifyClients(data) {
    const clients = await self.clients.matchAll({ type: 'window' });
    clients.forEach(client => client.postMessage(data));
}

/* =========================================================================
 * INSTALL EVENT — Pre-cache essential assets
 * ========================================================================= */

self.addEventListener('install', (event) => {
    console.log('[SW] Installing service worker:', CACHE_VERSION);

    event.waitUntil(
        caches.open(CACHE_VERSION)
            .then(cache => {
                console.log('[SW] Pre-caching app shell assets');

                /* Local assets — must all succeed for install to complete */
                const localPromise = cache.addAll(PRECACHE_ASSETS);

                /*
                 * CDN assets — best effort. Failures are silently ignored so
                 * a CDN outage doesn't block service worker installation.
                 * These will be cached at runtime on the next page load anyway.
                 */
                const cdnPromise = Promise.allSettled(
                    PRECACHE_CDN_ASSETS.map(url =>
                        fetch(url, { mode: 'cors' })
                            .then(resp => {
                                if (resp.ok) return cache.put(url, resp);
                            })
                            .catch(() => console.warn('[SW] CDN precache skipped:', url))
                    )
                );

                /*
                 * Local vendor fallback files — best effort.
                 * These may not exist if the download-vendor script hasn't run.
                 */
                const vendorPromise = Promise.allSettled(
                    PRECACHE_VENDOR_ASSETS.map(path =>
                        fetch(path)
                            .then(resp => {
                                if (resp.ok) return cache.put(path, resp);
                            })
                            .catch(() => {})
                    )
                );

                return Promise.all([localPromise, cdnPromise, vendorPromise]);
            })
            .then(() => {
                /*
                 * Activate immediately so critical fixes (e.g., offline/CDN
                 * caching) take effect on the very next page load.
                 *
                 * Previously (#83) skipWaiting was omitted to let users control
                 * when updates activate via the "Refresh" notification. However,
                 * this caused the old SW (which doesn't cache CDN resources) to
                 * remain in control indefinitely, leaving offline support broken
                 * until the user happened to close every tab.
                 *
                 * The controllerchange listener in app.js will auto-reload the
                 * page when this new SW takes over, ensuring fresh HTML + cached
                 * CDN assets are served.
                 */
                console.log('[SW] Activating immediately via skipWaiting');
                return self.skipWaiting();
            })
    );
});

/* =========================================================================
 * ACTIVATE EVENT — Clean up old caches
 * ========================================================================= */

self.addEventListener('activate', (event) => {
    console.log('[SW] Activating service worker:', CACHE_VERSION);

    event.waitUntil(
        caches.keys()
            .then(cacheNames => {
                /* Delete any caches that don't match the current version */
                return Promise.all(
                    cacheNames
                        .filter(name => name !== CACHE_VERSION && name !== RECENT_CACHE)
                        .map(name => {
                            console.log('[SW] Deleting old cache:', name);
                            return caches.delete(name);
                        })
                );
            })
            .then(() => {
                /* Take control of all open tabs immediately */
                return self.clients.claim();
            })
    );
});

/* =========================================================================
 * FETCH EVENT — Network-first strategy with offline fallback
 *
 * Strategy per resource type:
 *   1. Trusted CDNs  → Network-first, cache for offline (Bootstrap, FA, jQuery)
 *   2. Other CDNs    → Network-only (analytics, third-party scripts)
 *   3. API requests  → Network-first, cache song pages for offline (#105)
 *   4. Local assets  → Network-first, cache on success, serve cache if offline
 *   5. Navigation    → Network-first, fall back to cached '/' for offline shell
 * ========================================================================= */

self.addEventListener('fetch', (event) => {
    const url = new URL(event.request.url);

    /* --- CDN / Third-party resources --- */
    if (url.origin !== self.location.origin) {
        /*
         * Trusted CDN resources (Bootstrap, Font Awesome, jQuery, etc.)
         * are cached with network-first strategy so the app shell renders
         * offline. These CDNs serve CORS headers, so cached responses
         * remain readable for SRI verification.
         */
        if (TRUSTED_CDN_ORIGINS.some(origin => url.origin === origin)) {
            event.respondWith(networkFirstWithCache(event.request));
            return;
        }
        /* Other third-party resources: let the browser handle normally */
        return;
    }

    /* --- API requests: network-first with cache for song pages (#105, #131) --- */
    if (url.pathname.startsWith('/api')) {
        const isSongPage = url.searchParams.get('page') === 'song';
        const songId = url.searchParams.get('id');
        event.respondWith(
            fetch(event.request)
                .then(async (response) => {
                    /* Cache song page API responses for offline access */
                    if (isSongPage && response.ok) {
                        const cache = await caches.open(RECENT_CACHE);
                        const existing = await cache.match(event.request);

                        if (existing) {
                            /* Compare content to detect updates (#131) */
                            const [newBody, oldBody] = await Promise.all([
                                response.clone().text(),
                                existing.text(),
                            ]);

                            if (newBody !== oldBody) {
                                if (autoUpdateOfflineSongs) {
                                    /* Auto-update: silently cache the new version */
                                    await cache.put(event.request, response.clone());
                                    notifyClients({
                                        type: 'SONG_UPDATED',
                                        songId,
                                        auto: true,
                                    });
                                } else {
                                    /* Manual mode: notify user, don't overwrite yet */
                                    notifyClients({
                                        type: 'SONG_UPDATE_AVAILABLE',
                                        songId,
                                        url: event.request.url,
                                    });
                                }
                            }
                            /* If content unchanged, refresh the cache timestamp */
                            else {
                                await cache.put(event.request, response.clone());
                            }
                        } else {
                            /* Not previously cached — just cache it */
                            await cache.put(event.request, response.clone());
                        }
                    }
                    return response;
                })
                .catch(() => {
                    /* Offline: try recently viewed cache for song pages */
                    if (isSongPage) {
                        return caches.match(event.request).then(cached => {
                            if (cached) return cached;
                            return new Response(
                                JSON.stringify({ error: 'You appear to be offline.' }),
                                { status: 503, headers: { 'Content-Type': 'application/json' } }
                            );
                        });
                    }
                    return new Response(
                        JSON.stringify({ error: 'You appear to be offline. Please check your connection.' }),
                        { status: 503, headers: { 'Content-Type': 'application/json' } }
                    );
                })
        );
        return;
    }

    /* --- Song data (served via API): network-first, cache for offline (#154) --- */
    if (url.pathname === '/api' && url.searchParams.get('action') === 'songs_json') {
        event.respondWith(networkFirstWithCache(event.request));
        return;
    }

    /* --- Navigation requests: network-first, offline shell fallback --- */
    /* Deduplicates concurrent fetches for the same URL (#140) */
    if (event.request.mode === 'navigate') {
        const navKey = url.pathname + url.search;
        const inflight = inflightNavigations.get(navKey);

        if (inflight) {
            /* Another fetch for this URL is already in-flight — share it */
            event.respondWith(inflight.then(r => r.clone()));
            return;
        }

        const navigationPromise = fetch(event.request)
            .then(response => {
                /* Only cache successful (2xx) responses — never cache
                 * redirects (301/302) as that causes infinite redirect
                 * loops when served from cache (#140) */
                if (response.ok) {
                    const clone = response.clone();
                    caches.open(CACHE_VERSION).then(cache => {
                        cache.put(event.request, clone);
                    });
                }
                return response;
            })
            .catch(() => {
                /* Offline — serve cached version, app shell, or branded fallback */
                return caches.match(event.request)
                    .then(cached => cached || caches.match('/'))
                    .then(resp => resp || offlineFallbackResponse());
            })
            .finally(() => {
                inflightNavigations.delete(navKey);
            });

        inflightNavigations.set(navKey, navigationPromise);
        event.respondWith(navigationPromise.then(r => r.clone()));
        return;
    }

    /* --- All other local assets: network-first with cache fallback --- */
    event.respondWith(networkFirstWithCache(event.request));
});

/* =========================================================================
 * HELPER FUNCTIONS
 * ========================================================================= */

/**
 * Self-contained offline fallback page.
 * Shown when the user is offline AND no cached version of the page exists
 * (e.g., first launch of a freshly installed PWA with no network).
 * All styles and assets are inlined so no external requests are needed.
 */
const OFFLINE_FALLBACK_HTML = `<!DOCTYPE html>
<html lang="en" data-bs-theme="light">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
<title>iHymns — Offline</title>
<style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{
  --accent:#6366f1;--accent-end:#8b5cf6;
  --bg:#f8fafc;--card:#fff;--text:#1e293b;--text-sec:#64748b;--text-muted:#94a3b8;
  --radius:16px;--shadow:0 4px 24px rgba(0,0,0,.08);
}
@media(prefers-color-scheme:dark){:root{
  --accent:#818cf8;--accent-end:#a78bfa;
  --bg:#0f172a;--card:#1e293b;--text:#f1f5f9;--text-sec:#94a3b8;--text-muted:#64748b;
  --shadow:0 4px 24px rgba(0,0,0,.3);
}}
html,body{height:100%;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;
  -webkit-font-smoothing:antialiased;background:var(--bg);color:var(--text)}
body{display:flex;align-items:center;justify-content:center;padding:24px;
  padding-top:env(safe-area-inset-top,0);padding-bottom:env(safe-area-inset-bottom,0)}
.offline-wrap{text-align:center;max-width:420px;width:100%}
.offline-icon{margin:0 auto 28px;width:88px;height:88px;border-radius:50%;
  background:linear-gradient(135deg,var(--accent),var(--accent-end));
  display:flex;align-items:center;justify-content:center;
  box-shadow:0 8px 32px rgba(99,102,241,.25);animation:pulse-glow 3s ease-in-out infinite}
.offline-icon svg{width:44px;height:44px;opacity:.95}
@keyframes pulse-glow{0%,100%{box-shadow:0 8px 32px rgba(99,102,241,.25)}
  50%{box-shadow:0 8px 48px rgba(99,102,241,.4)}}
.offline-card{background:var(--card);border-radius:var(--radius);padding:32px 28px;
  box-shadow:var(--shadow)}
h1{font-size:1.5rem;font-weight:700;margin-bottom:8px;
  background:linear-gradient(135deg,var(--accent),var(--accent-end));
  -webkit-background-clip:text;-webkit-text-fill-color:transparent;
  background-clip:text}
.subtitle{font-size:.95rem;color:var(--text-sec);margin-bottom:24px;line-height:1.5}
.divider{width:48px;height:3px;border-radius:2px;margin:0 auto 24px;
  background:linear-gradient(90deg,var(--accent),var(--accent-end))}
.help-text{font-size:.875rem;color:var(--text-muted);line-height:1.6;margin-bottom:24px}
.help-text p{margin-bottom:12px}
.retry-btn{display:inline-flex;align-items:center;gap:8px;padding:12px 28px;
  border:none;border-radius:50px;font-size:.95rem;font-weight:600;cursor:pointer;
  background:linear-gradient(135deg,var(--accent),var(--accent-end));color:#fff;
  box-shadow:0 4px 16px rgba(99,102,241,.3);transition:transform .15s ease,box-shadow .15s ease}
.retry-btn:hover{transform:translateY(-1px);box-shadow:0 6px 24px rgba(99,102,241,.4)}
.retry-btn:active{transform:translateY(0);box-shadow:0 2px 8px rgba(99,102,241,.3)}
.retry-icon{display:inline-block;width:18px;height:18px;transition:transform .3s ease}
.retry-btn:hover .retry-icon{transform:rotate(180deg)}
.brand{margin-top:28px;font-size:.8rem;color:var(--text-muted);letter-spacing:.02em}
@media(prefers-reduced-motion:reduce){
  .offline-icon{animation:none}
  .retry-icon{transition:none}
}
</style>
</head>
<body>
<div class="offline-wrap">
  <div class="offline-icon">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"
         stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <line x1="1" y1="1" x2="23" y2="23"/>
      <path d="M16.72 11.06A10.94 10.94 0 0 1 19 12.55"/>
      <path d="M5 12.55a10.94 10.94 0 0 1 5.17-2.39"/>
      <path d="M10.71 5.05A16 16 0 0 1 22.56 9"/>
      <path d="M1.42 9a15.91 15.91 0 0 1 4.7-2.88"/>
      <path d="M8.53 16.11a6 6 0 0 1 6.95 0"/>
      <line x1="12" y1="20" x2="12.01" y2="20"/>
    </svg>
  </div>
  <div class="offline-card">
    <h1>You're Offline</h1>
    <p class="subtitle">iHymns needs an internet connection to load for the first time.</p>
    <div class="divider"></div>
    <div class="help-text">
      <p>Once you've opened iHymns with a connection, it will cache everything you need for offline use.</p>
      <p>You can also download entire songbooks for offline access from Settings.</p>
    </div>
    <button class="retry-btn" onclick="window.location.reload()">
      <svg class="retry-icon" viewBox="0 0 24 24" fill="none"
           stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
        <polyline points="23 4 23 10 17 10"/>
        <path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10"/>
      </svg>
      Try Again
    </button>
  </div>
  <p class="brand">iHymns — Christian Hymns &amp; Worship Songs</p>
</div>
</body>
</html>`;

/**
 * Return the offline fallback page as a Response.
 * @returns {Response}
 */
function offlineFallbackResponse() {
    return new Response(OFFLINE_FALLBACK_HTML, {
        status: 503,
        statusText: 'Service Unavailable',
        headers: { 'Content-Type': 'text/html; charset=UTF-8' }
    });
}

/**
 * Network-first caching strategy.
 * Tries the network first; on success, caches the response.
 * On failure (offline), serves from cache if available.
 *
 * @param {Request} request The fetch request
 * @returns {Promise<Response>} The response
 */
async function networkFirstWithCache(request) {
    try {
        /* Try network first */
        const networkResponse = await fetch(request);

        /* Cache the successful response */
        if (networkResponse.ok) {
            const cache = await caches.open(CACHE_VERSION);
            cache.put(request, networkResponse.clone());
        }

        return networkResponse;

    } catch (error) {
        /* Network failed — try cache */
        const cachedResponse = await caches.match(request);
        if (cachedResponse) {
            return cachedResponse;
        }

        /* Nothing in cache either — show the branded offline page */
        return offlineFallbackResponse();
    }
}

/* =========================================================================
 * MESSAGE EVENT — Handle SKIP_WAITING from the client (#83)
 *
 * When the user clicks the "Refresh" button in the update notification,
 * the client sends a { type: 'SKIP_WAITING' } message. This tells the
 * waiting service worker to activate immediately, replacing the old one.
 * The client then receives a 'controllerchange' event and reloads.
 * ========================================================================= */

self.addEventListener('message', (event) => {
    if (!event.data) return;

    if (event.data.type === 'SKIP_WAITING') {
        console.log('[SW] Received SKIP_WAITING — activating now');
        self.skipWaiting();
    }

    /* Download all songs for offline use */
    if (event.data.type === 'CACHE_ALL_SONGS' && Array.isArray(event.data.songIds)) {
        const songIds = event.data.songIds;
        const total = songIds.length;
        let completed = 0;
        let failed = 0;

        caches.open(RECENT_CACHE).then(async (cache) => {
            /* Process in batches of 5 to avoid overwhelming the server */
            const BATCH_SIZE = 5;
            for (let i = 0; i < songIds.length; i += BATCH_SIZE) {
                const batch = songIds.slice(i, i + BATCH_SIZE);
                const results = await Promise.allSettled(
                    batch.map(async (id) => {
                        const url = `/api?page=song&id=${encodeURIComponent(id)}`;
                        /* Skip if already cached */
                        const existing = await cache.match(url);
                        if (existing) { completed++; return; }
                        const response = await fetch(url);
                        if (response.ok) {
                            await cache.put(url, response);
                            completed++;
                        } else {
                            failed++;
                        }
                    })
                );

                /* Report progress back to client */
                const clients = await self.clients.matchAll();
                clients.forEach(client => {
                    client.postMessage({
                        type: 'CACHE_ALL_SONGS_PROGRESS',
                        completed,
                        failed,
                        total,
                    });
                });
            }

            /* Remove the LRU limit for bulk downloads — keep all songs */
        });
    }

    /* Set auto-update preference (#132) */
    if (event.data.type === 'SET_AUTO_UPDATE') {
        autoUpdateOfflineSongs = !!event.data.enabled;
        console.log('[SW] Auto-update offline songs:', autoUpdateOfflineSongs);
    }

    /* Accept a pending song update — cache the fresh version (#131) */
    if (event.data.type === 'UPDATE_SONG_CACHE' && event.data.url) {
        try {
            const cacheUrl = new URL(event.data.url, self.location.origin);
            if (cacheUrl.origin !== self.location.origin) return;
        } catch { return; }

        caches.open(RECENT_CACHE).then(async (cache) => {
            try {
                const response = await fetch(event.data.url);
                if (response.ok) {
                    await cache.put(event.data.url, response);
                    notifyClients({
                        type: 'SONG_UPDATED',
                        songId: event.data.songId,
                        auto: false,
                    });
                }
            } catch (error) {
                console.warn('[SW] Failed to update cached song:', error.message);
            }
        });
    }

    /* Proactively cache a recently viewed song page (#105) */
    if (event.data.type === 'CACHE_SONG' && event.data.url) {
        /* Validate URL origin to prevent cache poisoning */
        try {
            const cacheUrl = new URL(event.data.url, self.location.origin);
            if (cacheUrl.origin !== self.location.origin) return;
        } catch { return; }

        caches.open(RECENT_CACHE).then(async (cache) => {
            try {
                const response = await fetch(event.data.url);
                if (response.ok) {
                    await cache.put(event.data.url, response);
                    /* Evict oldest entries if over limit */
                    const keys = await cache.keys();
                    if (keys.length > RECENT_CACHE_LIMIT) {
                        const toDelete = keys.slice(0, keys.length - RECENT_CACHE_LIMIT);
                        await Promise.all(toDelete.map(k => cache.delete(k)));
                    }
                }
            } catch (error) {
                console.warn('[SW] Failed to cache song:', event.data.url, error.message);
            }
        });
    }
});
