/**
 * iHymns — Shared Constants
 *
 * Copyright (c) 2026 iHymns. All rights reserved.
 *
 * PURPOSE:
 * Centralised localStorage key names and other shared constants.
 * All modules import keys from here to prevent key-name drift (#139).
 */

/* ── localStorage Keys ─────────────────────────────────────────────────── */

/* Core data */
export const STORAGE_FAVORITES      = 'ihymns_favorites';
export const STORAGE_SETLISTS       = 'ihymns_setlists';
export const STORAGE_HISTORY        = 'ihymns_history';
export const STORAGE_SEARCH_HISTORY = 'ihymns_search_history';
export const STORAGE_CUSTOM_TAGS    = 'ihymns_custom_tags';
export const STORAGE_OWNER_ID       = 'ihymns_owner_id';

/* Per-device flag: set once the local recently-viewed history has been
   pushed to the server (tblSongHistory) for the signed-in account, so the
   one-time backfill doesn't re-stack rows on every login (WS-G #1019). */
export const STORAGE_HISTORY_BACKFILLED = 'ihymns_history_backfilled';

/* User preferences */
export const STORAGE_THEME              = 'ihymns_theme';
export const STORAGE_FONT_SIZE          = 'ihymns_fontSize';
export const STORAGE_REDUCE_MOTION      = 'ihymns_reduceMotion';
export const STORAGE_REDUCE_TRANSPARENCY = 'ihymns_reduceTransparency';
export const STORAGE_TRANSITION         = 'ihymns_transition';
export const STORAGE_DEFAULT_SONGBOOK   = 'ihymns_default_songbook';
export const STORAGE_AUTO_UPDATE_SONGS  = 'ihymns_auto_update_songs';
export const STORAGE_NUMPAD_LIVE_SEARCH = 'ihymns_numpad_live_search';
export const STORAGE_SEARCH_LYRICS      = 'ihymns_search_lyrics';
export const STORAGE_DISPLAY            = 'ihymns_display';

/* Status & consent */
export const STORAGE_ANALYTICS_CONSENT  = 'ihymns_analytics_consent';
export const STORAGE_ANALYTICS_DEBUG    = 'ihymns_analytics_debug';
export const STORAGE_DISCLAIMER_ACCEPTED = 'ihymns_disclaimer_accepted';
export const STORAGE_PWA_BANNER_DISMISSED = 'ihymns_pwa_banner_dismissed';

export const STORAGE_RECENT_SONGBOOKS = 'ihymns_recent_songbooks';

/* Auth (cross-subdomain SPA session token + cached user object) */
export const STORAGE_AUTH_TOKEN         = 'ihymns_auth_token';
export const STORAGE_AUTH_USER          = 'ihymns_auth_user';

/* Accessibility — Colour Vision Deficiency mode (#319) */
export const STORAGE_CVD_MODE           = 'ihymns_cvd_mode';

/* Offline downloads — whether to also cache MIDI audio when bulk-saving songs.
   CANONICAL key, value '1' | '0'. */
export const STORAGE_OFFLINE_INCLUDE_AUDIO = 'ihymns_offline_include_audio';

/* The SAME preference under the key `Settings.set('includeAudioOffline', …)`
   derives from its `ihymns_` prefix, value 'true' | 'false' (#1597 RC7).
   ELI5: the setting accidentally ended up written down in two places with two
   different spellings, and the two halves of the app each read a different one.
   Detail: Settings has always been the writer via its prefix-derived key,
   while offline-ui.js read the canonical key above — so "include audio in
   offline downloads" was inert for tile downloads from the day it shipped.
   Settings now mirror-writes the canonical key; this legacy name is declared
   here (rather than hard-coded in the reader) so the pair is visible in the
   ONE place key names live (#139), and is still read so an existing choice
   survives the upgrade. Remove once Settings no longer writes it. */
export const STORAGE_OFFLINE_INCLUDE_AUDIO_LEGACY = 'ihymns_includeAudioOffline';

/* Dynamic key prefix (appended with song ID) */
export const STORAGE_TRANSPOSE_PREFIX   = 'ihymns_transpose_';

/* ── Service-worker cache bucket names (#1597) ────────────────────────────
   ELI5: the names of the boxes the offline downloads live in, written down
   once so the app and the service worker can never disagree about them.

   Detail: `service-worker.js.php` is a CLASSIC worker generated by PHP — it
   cannot `import` this module, so it declares the same names itself. These
   exports are the CLIENT-side half of that contract; the two must be kept in
   step by hand, and they are listed together here so the pairing is obvious to
   the next person who adds a bucket. This is the same drift-prevention job
   this file already does for localStorage keys (#139).

   CACHE_SONGS_SAVED  — deliberately downloaded songs. NEVER trimmed. Shrinks
                        only when the user removes a songbook (#1597 RC1).
   CACHE_SONGS_RECENT — incidental song views. Capped and trimmed oldest-first.
   CACHE_MEDIA        — audio + sheet music. Historical camelCase name kept
                        deliberately: renaming it would discard every user's
                        already-downloaded audio (#1597 RC2). */
export const CACHE_SONGS_SAVED  = 'ihymns-saved-songs';
export const CACHE_SONGS_RECENT = 'ihymns-recent-songs';
export const CACHE_MEDIA        = 'iHymns-media-v1';

/* ── Custom DOM event names (#1581) ──────────────────────────────────────
   ELI5: every custom event the app fires has its name written down once,
   here, so two files can never disagree about it.
   Detail: DOM event types are CASE-SENSITIVE, so `ihymns:x` and `iHymns:x`
   are different events entirely — a casing typo is a silent no-op with no
   error. That is exactly what broke the Settings language filter → Song of
   the Day refresh. Canonical prefix is lowercase `ihymns:` (8 of the 10
   pre-existing names already used it).
   https://developer.mozilla.org/docs/Web/API/EventTarget/addEventListener */
export const EVT_AUTH_CHANGED             = 'ihymns:auth-changed';
export const EVT_REFRESH_REQUESTED        = 'ihymns:refresh-requested';
export const EVT_REFRESH_COMPLETE         = 'ihymns:refresh-complete';
export const EVT_FETCH_FAILED             = 'ihymns:fetch-failed';
export const EVT_FETCH_SUCCEEDED          = 'ihymns:fetch-succeeded';
export const EVT_LANGUAGE_FILTER_CHANGED  = 'ihymns:language-filter-changed';
export const EVT_OFFLINE_SETTINGS_CHANGED = 'ihymns:offline-settings-changed';

/* ── Songbook Name Lookup ─────────────────────────────────────────────── */

/**
 * Canonical mapping of songbook abbreviation → full display name.
 * Used by songbookLabel() to render responsive names across the app.
 */
export const SONGBOOK_NAMES = {
    CP:   'Carol Praise',
    JP:   'Junior Praise',
    MP:   'Mission Praise',
    SDAH: 'Seventh-day Adventist Hymnal',
    CH:   'The Church Hymnal',
    Misc: 'Miscellaneous',
};

/* Local HTML escaper — kept inline to keep constants.js DOM-free and
   avoid pulling utils/html.js into the dependency graph. The output of
   songbookLabel is interpolated into innerHTML across many modules, so
   any caller-supplied abbr/fullName must be escaped here at the source
   to satisfy CodeQL's "DOM text reinterpreted as HTML" rule and stay
   safe even when callers forget to escape. */
const _ESC_MAP = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };
function _escSongbook(s) {
    return String(s ?? '').replace(/[&<>"']/g, c => _ESC_MAP[c]);
}

/**
 * Return responsive songbook label HTML showing full name by default
 * and abbreviation on narrow screens. Both are always present in the
 * DOM; CSS toggles visibility based on viewport width.
 *
 * @param {string} abbr  Songbook abbreviation (e.g. 'MP')
 * @param {string} [fullName]  Optional override for full name
 * @returns {string} HTML with both spans
 */
export function songbookLabel(abbr, fullName) {
    /* #1531 — resolve order: an explicit override → the client songbook
       registry (covers EVERY songbook, loaded once from /api?action=songbooks)
       → the six hardcoded fallbacks → the abbreviation. This is what makes
       list views (setlists, favourites, search, home) show the full Songbook
       NAME rather than the abbreviation, for all songbooks not just the six. */
    const full = fullName || songbookFullName(abbr) || SONGBOOK_NAMES[abbr] || abbr;
    const safeAbbr = _escSongbook(abbr);
    if (full === abbr) return safeAbbr; /* no full name available */
    return `<span class="songbook-name-full">${_escSongbook(full)}</span><span class="songbook-name-abbr">${safeAbbr}</span>`;
}

/* ── #1531 — Client songbook registry ──────────────────────────────────────
   The ONE abbr → { name, isOfficial } source so every list view shows the full
   Songbook NAME (not the abbreviation) for ALL songbooks — not just the six in
   SONGBOOK_NAMES above. Populated once from /api?action=songbooks at app init
   (App.init() calls loadSongbookRegistry); songbookLabel()/songbookFullName()
   read it synchronously. Best-effort: if the fetch hasn't completed (or failed)
   the resolvers fall back to SONGBOOK_NAMES / the abbreviation, so nothing
   breaks — the name simply fills in once the registry loads. */
const _SONGBOOK_REGISTRY = new Map();

/** Load the songbook registry once. Fire-and-forget from App.init(). */
export async function loadSongbookRegistry(apiUrl) {
    if (!apiUrl) return;
    try {
        const res = await fetch(`${apiUrl}?action=songbooks`, {
            headers: { 'X-Requested-With': 'XMLHttpRequest' },
        });
        if (!res.ok) return;
        const data = await res.json();
        for (const book of (data.songbooks || [])) {
            if (book && book.id) {
                _SONGBOOK_REGISTRY.set(book.id, {
                    name: book.name || '',
                    /* IsOfficial is a strict bool from the API (#502); default
                       to true when a book is somehow absent so an unknown book
                       is never mis-flagged as "unofficial". */
                    isOfficial: book.isOfficial !== false,
                });
            }
        }
    } catch {
        /* Best-effort — songbookLabel falls back to SONGBOOK_NAMES / abbr. */
    }
}

/** Full name for a songbook abbreviation from the registry, or null. */
export function songbookFullName(abbr) {
    const entry = _SONGBOOK_REGISTRY.get(abbr);
    return (entry && entry.name) || null;
}

/** Whether a songbook is official (registry), defaulting to true if unknown.
   Enables the "Unofficial → show writing team" treatment (#1531 part 2). */
export function songbookIsOfficial(abbr) {
    const entry = _SONGBOOK_REGISTRY.get(abbr);
    return entry ? entry.isOfficial : true;
}
