<?php
/**
 * Service Worker PHP Wrapper (#81)
 *
 * This file is served as JavaScript but generated by PHP so that
 * the cache version is automatically derived from infoAppVer.php.
 * The .htaccess rule rewrites /service-worker.js → service-worker.js.php.
 *
 * Content-Type is set to JavaScript so the browser treats it correctly.
 */
header('Content-Type: application/javascript; charset=UTF-8');
header('Cache-Control: no-cache, no-store, must-revalidate');
header('Service-Worker-Allowed: /');

require_once __DIR__ . '/includes/infoAppVer.php';
$swVersion = $app['Application']['Version']['Number'] ?? '0.0.0';
?>
/**
 * iHymns — Service Worker
 *
 * Copyright (c) 2026 MWBM Partners Ltd. All rights reserved.
 *
 * PURPOSE:
 * Provides offline support and caching for the iHymns PWA.
 *
 * STRATEGY:
 * "Network-first with offline fallback" — as per requirements:
 *   - Always try to load content from the host (network) first
 *   - Only fall back to cached content when the network is unreachable
 *   - Pre-caches essential app shell assets for instant offline access
 *   - CDN resources are NOT cached to avoid cache poisoning
 *
 * CACHE MANAGEMENT:
 *   - Cache version is derived from infoAppVer.php automatically
 *   - Old caches are automatically cleaned up on activation
 *
 * NOTE: This file is generated by PHP (service-worker.js.php) and served
 * via .htaccess rewrite as /service-worker.js. The PHP wrapper injects
 * the current app version into the CACHE_VERSION constant so it always
 * stays in sync with infoAppVer.php (#81).
 */

/* =========================================================================
 * CACHE CONFIGURATION
 * ========================================================================= */

/**
 * Cache version — derived from the application version in infoAppVer.php.
 * When the version is bumped by CI/CD, the service worker automatically
 * gets a new cache key, triggering a full cache purge on next load.
 */
const CACHE_VERSION = 'ihymns-v<?= $swVersion ?>';

/**
 * Recently viewed songs cache (#105).
 * Separate bucket so it survives app version cache purges.
 * Limited to 20 entries via eviction in the message handler.
 */
const RECENT_CACHE = 'ihymns-recent-songs';
const RECENT_CACHE_LIMIT = 20;

/**
 * Assets to pre-cache during service worker installation.
 * These are the essential app shell files needed for offline access.
 * Only local files — CDN resources are never cached.
 */
const PRECACHE_ASSETS = [
    '/',
    '/css/app.css',
    '/css/print.css',
    '/js/app.js',
    '/js/modules/router.js',
    '/js/modules/transitions.js',
    '/js/modules/settings.js',
    '/js/modules/search.js',
    '/js/modules/favorites.js',
    '/js/modules/pwa.js',
    '/js/modules/shuffle.js',
    '/js/modules/numpad.js',
    '/js/modules/share.js',
    '/js/modules/compare.js',
    '/js/modules/shortcuts.js',
    '/js/modules/request.js',
    '/js/modules/transpose.js',
    '/js/modules/reading-progress.js',
    '/js/modules/songbook-index.js',
    '/js/modules/search-history.js',
    '/manifest.json',
    '/assets/favicon.svg',
];

/* =========================================================================
 * INSTALL EVENT — Pre-cache essential assets
 * ========================================================================= */

self.addEventListener('install', (event) => {
    console.log('[SW] Installing service worker:', CACHE_VERSION);

    event.waitUntil(
        caches.open(CACHE_VERSION)
            .then(cache => {
                console.log('[SW] Pre-caching app shell assets');
                return cache.addAll(PRECACHE_ASSETS);
            })
            /*
             * NOTE (#83): We intentionally do NOT call self.skipWaiting() here.
             * The new service worker waits in the "installed" state until the user
             * clicks the "Refresh" button in the update notification, which sends
             * a SKIP_WAITING message (handled below). This gives users control
             * over when the update activates, preventing mid-session disruption.
             */
    );
});

/* =========================================================================
 * ACTIVATE EVENT — Clean up old caches
 * ========================================================================= */

self.addEventListener('activate', (event) => {
    console.log('[SW] Activating service worker:', CACHE_VERSION);

    event.waitUntil(
        caches.keys()
            .then(cacheNames => {
                /* Delete any caches that don't match the current version */
                return Promise.all(
                    cacheNames
                        .filter(name => name !== CACHE_VERSION && name !== RECENT_CACHE)
                        .map(name => {
                            console.log('[SW] Deleting old cache:', name);
                            return caches.delete(name);
                        })
                );
            })
            .then(() => {
                /* Take control of all open tabs immediately */
                return self.clients.claim();
            })
    );
});

/* =========================================================================
 * FETCH EVENT — Network-first strategy with offline fallback
 *
 * Strategy per resource type:
 *   1. CDN resources → Network-only (never cache third-party)
 *   2. API requests  → Network-first, no caching (dynamic data)
 *   3. Local assets  → Network-first, cache on success, serve cache if offline
 *   4. Navigation    → Network-first, fall back to cached '/' for offline shell
 * ========================================================================= */

self.addEventListener('fetch', (event) => {
    const url = new URL(event.request.url);

    /* --- CDN / Third-party resources: network-only, never cache --- */
    if (url.origin !== self.location.origin) {
        /* Let the browser handle CDN requests normally */
        return;
    }

    /* --- API requests: network-first with cache for song pages (#105) --- */
    if (url.pathname.startsWith('/api')) {
        const isSongPage = url.searchParams.get('page') === 'song';
        event.respondWith(
            fetch(event.request)
                .then(response => {
                    /* Cache song page API responses for offline access */
                    if (isSongPage && response.ok) {
                        const clone = response.clone();
                        caches.open(RECENT_CACHE).then(cache => {
                            cache.put(event.request, clone);
                        });
                    }
                    return response;
                })
                .catch(() => {
                    /* Offline: try recently viewed cache for song pages */
                    if (isSongPage) {
                        return caches.match(event.request).then(cached => {
                            if (cached) return cached;
                            return new Response(
                                JSON.stringify({ error: 'You appear to be offline.' }),
                                { status: 503, headers: { 'Content-Type': 'application/json' } }
                            );
                        });
                    }
                    return new Response(
                        JSON.stringify({ error: 'You appear to be offline. Please check your connection.' }),
                        { status: 503, headers: { 'Content-Type': 'application/json' } }
                    );
                })
        );
        return;
    }

    /* --- Song data (songs.json): network-first, cache for offline --- */
    if (url.pathname.endsWith('/songs.json')) {
        event.respondWith(networkFirstWithCache(event.request));
        return;
    }

    /* --- Navigation requests: network-first, offline shell fallback --- */
    if (event.request.mode === 'navigate') {
        event.respondWith(
            fetch(event.request)
                .then(response => {
                    /* Cache the navigation response for offline */
                    const clone = response.clone();
                    caches.open(CACHE_VERSION).then(cache => {
                        cache.put(event.request, clone);
                    });
                    return response;
                })
                .catch(() => {
                    /* Offline — serve cached version or the app shell */
                    return caches.match(event.request)
                        .then(cached => cached || caches.match('/'));
                })
        );
        return;
    }

    /* --- All other local assets: network-first with cache fallback --- */
    event.respondWith(networkFirstWithCache(event.request));
});

/* =========================================================================
 * HELPER FUNCTIONS
 * ========================================================================= */

/**
 * Network-first caching strategy.
 * Tries the network first; on success, caches the response.
 * On failure (offline), serves from cache if available.
 *
 * @param {Request} request The fetch request
 * @returns {Promise<Response>} The response
 */
async function networkFirstWithCache(request) {
    try {
        /* Try network first */
        const networkResponse = await fetch(request);

        /* Cache the successful response */
        if (networkResponse.ok) {
            const cache = await caches.open(CACHE_VERSION);
            cache.put(request, networkResponse.clone());
        }

        return networkResponse;

    } catch (error) {
        /* Network failed — try cache */
        const cachedResponse = await caches.match(request);
        if (cachedResponse) {
            return cachedResponse;
        }

        /* Nothing in cache either — return a generic offline response */
        return new Response('Offline — content not available', {
            status: 503,
            statusText: 'Service Unavailable',
            headers: { 'Content-Type': 'text/plain' }
        });
    }
}

/* =========================================================================
 * MESSAGE EVENT — Handle SKIP_WAITING from the client (#83)
 *
 * When the user clicks the "Refresh" button in the update notification,
 * the client sends a { type: 'SKIP_WAITING' } message. This tells the
 * waiting service worker to activate immediately, replacing the old one.
 * The client then receives a 'controllerchange' event and reloads.
 * ========================================================================= */

self.addEventListener('message', (event) => {
    if (!event.data) return;

    if (event.data.type === 'SKIP_WAITING') {
        console.log('[SW] Received SKIP_WAITING — activating now');
        self.skipWaiting();
    }

    /* Proactively cache a recently viewed song page (#105) */
    if (event.data.type === 'CACHE_SONG' && event.data.url) {
        caches.open(RECENT_CACHE).then(async (cache) => {
            try {
                const response = await fetch(event.data.url);
                if (response.ok) {
                    await cache.put(event.data.url, response);
                    /* Evict oldest entries if over limit */
                    const keys = await cache.keys();
                    if (keys.length > RECENT_CACHE_LIMIT) {
                        const toDelete = keys.slice(0, keys.length - RECENT_CACHE_LIMIT);
                        await Promise.all(toDelete.map(k => cache.delete(k)));
                    }
                }
            } catch {
                /* Ignore network errors — song may already be cached */
            }
        });
    }
});
