/**
 * iHymns — Main Application Entry Point
 *
 * Copyright © 2026 MWBM Partners Ltd. All rights reserved.
 * This software is proprietary. Unauthorized copying, modification, or
 * distribution is strictly prohibited.
 *
 * Third-party components retain their respective licenses.
 *
 * PURPOSE:
 * This is the main JavaScript entry point for the iHymns web PWA.
 * It initialises all modules, loads song data, sets up the SPA router,
 * and orchestrates the application lifecycle.
 *
 * ARCHITECTURE:
 * - app.js (this file): orchestration, data loading, routing
 * - modules/songbook.js: songbook grid and song list views
 * - modules/song-view.js: individual song lyrics display
 * - modules/search.js: Fuse.js search index and search UI
 * - modules/favorites.js: favourites management (localStorage)
 * - modules/settings.js: dark mode, PWA install, update checker
 * - utils/helpers.js: shared DOM helpers and utilities
 */

/* =========================================================================
 * MODULE IMPORTS
 * ========================================================================= */

/* Import DOM helper functions from the shared utilities module */
import { $, getHashRoute, setHashRoute } from './utils/helpers.js';

/* Import the songbook grid and song list rendering functions */
import { renderSongbookGrid, renderSongList } from './modules/songbook.js';

/* Import the song detail (lyrics) view rendering function */
import { renderSongDetail } from './modules/song-view.js';

/* Import search initialisation, binding, and rendering functions */
import { initSearch, bindSearchInput } from './modules/search.js';

/* Import favourites rendering function */
import { renderFavorites } from './modules/favorites.js';

/* Import the in-app help view rendering function */
import { renderHelpView } from './modules/help.js';

/* Import settings/theme functions for dark mode, colourblind mode, install banner, and updates */
import { initTheme, bindThemeToggle, initInstallBanner, initUpdateChecker, initColourblindMode, toggleColourblindMode } from './modules/settings.js';

/* =========================================================================
 * APPLICATION STATE
 * ========================================================================= */

/**
 * appState holds the global application state.
 * - songData:  The parsed song database (loaded from data/songs.json)
 * - isLoading: Whether song data is currently being fetched
 * - currentView: The name of the currently active view (for routing)
 */
const appState = {
    songData: null,
    isLoading: true,
    currentView: 'home'
};

/* =========================================================================
 * DATA LOADING
 * ========================================================================= */

/**
 * loadSongData()
 *
 * Fetches the song database (songs.json) from the data/ directory.
 * The JSON file is generated by the parse-songs.js tool and contains
 * all songbooks and songs in a structured format.
 *
 * The path uses '../../../data/songs.json' because the web app lives in
 * appWeb/public_html_beta/ and the data file is at the project root's data/.
 * On a deployed server, this path may need to be adjusted (e.g., to a
 * PHP endpoint that serves the JSON, or a different relative path).
 *
 * @returns {Promise<object>} The parsed song data object
 * @throws {Error} If the fetch fails or JSON is invalid
 */
async function loadSongData() {
    /* Define possible paths where songs.json might be found.
       On the server, it lives at data/songs.json inside the deployed directory
       (copied there during CI/CD deployment). Same data across all environments. */
    const possiblePaths = [
        'data/songs.json',
        '../data/songs.json',
        '../../data/songs.json'
    ];

    /* Try each path until one succeeds */
    for (const dataPath of possiblePaths) {
        try {
            /* Fetch the JSON file from the server */
            const response = await fetch(dataPath);

            /* Check if the response is OK (HTTP 200) */
            if (response.ok) {
                /* Parse the JSON response into a JavaScript object */
                const data = await response.json();

                /* Log success to the console for debugging */
                console.log(`[iHymns] Song data loaded from ${dataPath}: ${data.songs.length} songs`);

                /* Return the parsed data */
                return data;
            }
        } catch (err) {
            /* This path didn't work, try the next one */
            continue;
        }
    }

    /* If no path worked, throw an error */
    throw new Error('Could not load songs.json from any expected path');
}

/* =========================================================================
 * SPA ROUTER
 * ========================================================================= */

/**
 * handleRoute()
 *
 * The main SPA router function. Reads the current URL hash and renders
 * the appropriate view in the #app-content container.
 *
 * Route patterns:
 *   #/               → Home (songbook grid)
 *   #/songbook/<ID>  → Song list for a specific songbook
 *   #/song/<SONG_ID> → Song detail view (lyrics)
 *   #/favorites      → Favourites view
 *   #/help           → Help view (future)
 *   (anything else)  → Home (fallback)
 */
function handleRoute() {
    /* Get the #app-content container where views are rendered */
    const container = $('#app-content');

    /* If song data hasn't loaded yet, do nothing (loading spinner is shown) */
    if (!appState.songData) {
        return;
    }

    /* Parse the current URL hash into route segments */
    const route = getHashRoute();

    /* Extract the first segment to determine the view type */
    const viewType = route.segments[0] || '';

    /* Extract the second segment (used as an ID parameter) */
    const viewParam = route.segments[1] || '';

    /* Route to the appropriate view based on the first segment */
    switch (viewType) {

        /* --- Songbook View: show all songs in a specific songbook --- */
        case 'songbook':
            /* Update the current view name in app state */
            appState.currentView = 'songbook';

            /* Render the song list for the specified songbook ID */
            renderSongList(appState.songData, viewParam, container);

            /* Update the active nav link */
            updateActiveNav('songbooks');
            break;

        /* --- Song Detail View: show lyrics for a specific song --- */
        case 'song':
            /* Update the current view name in app state */
            appState.currentView = 'song';

            /* Find the song object by its ID (e.g., "CH-0003") */
            const song = appState.songData.songs.find(s => s.id === viewParam);

            /* If the song exists, render its detail view */
            if (song) {
                renderSongDetail(song, container);
            } else {
                /* Song not found: show an error message */
                /* Use textContent to safely display the user-controlled viewParam */
                container.innerHTML = '';
                const errorDiv = document.createElement('div');
                errorDiv.className = 'text-center py-5 view-fade-in';
                errorDiv.innerHTML = `
                    <i class="bi bi-exclamation-triangle fs-1 text-warning"></i>
                    <h3 class="mt-3">Song Not Found</h3>
                    <p class="text-muted"></p>
                    <a href="#/" class="btn btn-primary mt-2">
                        <i class="bi bi-house me-1"></i>Back to Songbooks
                    </a>
                `;
                /* Safely set the user-controlled parameter as text, not HTML */
                errorDiv.querySelector('p').textContent = `The song "${viewParam}" could not be found.`;
                container.appendChild(errorDiv);
            }

            /* Clear the active nav (song detail is not a nav item) */
            updateActiveNav('');
            break;

        /* --- Favourites View: show saved favourite songs --- */
        case 'favorites':
            /* Update the current view name in app state */
            appState.currentView = 'favorites';

            /* Render the favourites list */
            renderFavorites(appState.songData, container);

            /* Update the active nav link */
            updateActiveNav('favorites');
            break;

        /* --- Help View: placeholder for future in-app help --- */
        case 'help':
            /* Update the current view name in app state */
            appState.currentView = 'help';

            /* Render a simple help placeholder */
            renderHelpView(container);

            /* Update the active nav link */
            updateActiveNav('help');
            break;

        /* --- Home (default): show songbook grid --- */
        default:
            /* Update the current view name in app state */
            appState.currentView = 'home';

            /* Render the songbook grid (home view) */
            renderSongbookGrid(appState.songData, container);

            /* Update the active nav link */
            updateActiveNav('songbooks');
            break;
    }

    /* Scroll to the top of the page on each route change */
    window.scrollTo({ top: 0, behavior: 'smooth' });

    /* Update the browser tab title to reflect the current view */
    updateDocumentTitle(viewType, viewParam);
}

/**
 * updateDocumentTitle(viewType, viewParam)
 *
 * Updates the browser tab title based on the current route.
 * This helps users identify the page in their browser tabs and history,
 * and improves SEO for bookmarked/shared deep links.
 *
 * @param {string} viewType  - The view type segment (e.g., 'songbook', 'song', 'favorites')
 * @param {string} viewParam - The view parameter (e.g., songbook ID or song ID)
 */
function updateDocumentTitle(viewType, viewParam) {
    /* Base app name used as suffix in all titles */
    const baseName = 'iHymns';

    /* Build title based on the current view */
    switch (viewType) {

        case 'songbook': {
            /* Find the songbook name from the song data */
            const songbook = appState.songData.songbooks.find(sb => sb.id === viewParam);

            /* Set title to "Songbook Name — iHymns" */
            document.title = songbook
                ? `${songbook.name} — ${baseName}`
                : `Songbook — ${baseName}`;
            break;
        }

        case 'song': {
            /* Find the song from the song data */
            const song = appState.songData.songs.find(s => s.id === viewParam);

            /* Set title to "Song Title — Songbook — iHymns" */
            document.title = song
                ? `${song.title} — ${song.songbookName} #${song.number} — ${baseName}`
                : `Song — ${baseName}`;
            break;
        }

        case 'favorites':
            /* Set title for favourites view */
            document.title = `Favourites — ${baseName}`;
            break;

        case 'help':
            /* Set title for help view */
            document.title = `Help — ${baseName}`;
            break;

        default:
            /* Home/default: just the app name with tagline */
            document.title = `${baseName} — Christian Lyrics for Worship`;
            break;
    }
}

/**
 * updateActiveNav(navName)
 *
 * Updates the visual "active" state of navigation links in the navbar.
 * Only one nav link should appear active at a time.
 *
 * @param {string} navName - The nav item to mark active: 'songbooks', 'favorites', 'help', or ''
 */
function updateActiveNav(navName) {
    /* Get references to all navigation link elements */
    const navSongbooks = $('#nav-songbooks');
    const navFavorites = $('#nav-favorites');
    const navHelp = $('#nav-help');

    /* Remove 'active' class and aria-current from all nav links */
    [navSongbooks, navFavorites, navHelp].forEach(link => {
        if (link) {
            link.classList.remove('active');
            link.removeAttribute('aria-current');
        }
    });

    /* Map the navName to the corresponding element */
    const navMap = {
        'songbooks': navSongbooks,
        'favorites': navFavorites,
        'help': navHelp
    };

    /* Add 'active' class and aria-current to the matching nav link */
    const activeLink = navMap[navName];
    if (activeLink) {
        activeLink.classList.add('active');
        activeLink.setAttribute('aria-current', 'page');
    }
}

/* =========================================================================
 * NAVIGATION EVENT BINDING
 * ========================================================================= */

/**
 * bindNavigation()
 *
 * Binds click event listeners to the navbar navigation links.
 * Each link navigates to the corresponding hash route.
 */
function bindNavigation() {
    /* Brand/logo click: navigate to home (songbook grid) */
    const navBrand = $('#nav-brand');
    if (navBrand) {
        navBrand.addEventListener('click', (e) => {
            e.preventDefault();
            setHashRoute('/');
        });
    }

    /* Songbooks nav link: navigate to home */
    const navSongbooks = $('#nav-songbooks');
    if (navSongbooks) {
        navSongbooks.addEventListener('click', (e) => {
            e.preventDefault();
            setHashRoute('/');
        });
    }

    /* Favourites nav link: navigate to favourites view */
    const navFavorites = $('#nav-favorites');
    if (navFavorites) {
        navFavorites.addEventListener('click', (e) => {
            e.preventDefault();
            setHashRoute('/favorites');
        });
    }

    /* Help nav link: navigate to help view */
    const navHelp = $('#nav-help');
    if (navHelp) {
        navHelp.addEventListener('click', (e) => {
            e.preventDefault();
            setHashRoute('/help');
        });
    }

    /* Footer help link: navigate to help view */
    const footerHelp = $('#footer-help');
    if (footerHelp) {
        footerHelp.addEventListener('click', (e) => {
            e.preventDefault();
            setHashRoute('/help');
        });
    }
}

/* =========================================================================
 * SERVICE WORKER REGISTRATION
 * ========================================================================= */

/**
 * registerServiceWorker()
 *
 * Registers the PWA service worker for offline capability and caching.
 * Only registers if the browser supports service workers.
 */
async function registerServiceWorker() {
    /* Check if the browser supports service workers */
    if ('serviceWorker' in navigator) {
        try {
            /* Register the service worker script */
            const registration = await navigator.serviceWorker.register('service-worker.js');

            /* Log success for debugging */
            console.log('[iHymns] Service Worker registered:', registration.scope);
        } catch (error) {
            /* Log failure (non-critical — app still works without SW) */
            console.warn('[iHymns] Service Worker registration failed:', error);
        }
    }
}

/* =========================================================================
 * APPLICATION INITIALISATION
 * ========================================================================= */

/**
 * init()
 *
 * The main initialisation function. Called when the DOM is ready.
 * Performs the following steps:
 *   1. Initialise theme (dark/light mode)
 *   2. Bind navigation event listeners
 *   3. Load song data from JSON
 *   4. Initialise search index
 *   5. Bind search input events
 *   6. Handle the initial route
 *   7. Set up hash change listener for SPA routing
 *   8. Register service worker
 *   9. Initialise PWA install banner
 *  10. Start update checker
 */
async function init() {
    /* Log application start for debugging */
    console.log('[iHymns] Initialising application...');

    /* --- Step 1: Initialise theme --- */
    /* Apply the user's saved theme preference or system default */
    initTheme();

    /* Apply colourblind-friendly mode if previously enabled */
    initColourblindMode();

    /* Bind the dark mode toggle button event listener */
    bindThemeToggle();

    /* Bind the colourblind mode toggle button */
    const cbToggle = $('#cb-toggle');
    if (cbToggle) {
        cbToggle.addEventListener('click', () => {
            const newState = toggleColourblindMode();
            /* Update button visual to reflect state */
            cbToggle.classList.toggle('active', newState);
            cbToggle.setAttribute('aria-pressed', String(newState));
        });
        /* Set initial visual state */
        const cbEnabled = document.documentElement.getAttribute('data-theme-cb') === 'true';
        cbToggle.classList.toggle('active', cbEnabled);
        cbToggle.setAttribute('aria-pressed', String(cbEnabled));
    }

    /* --- Step 2: Bind navigation --- */
    /* Set up click handlers for all navbar links */
    bindNavigation();

    /* --- Step 3: Load song data --- */
    try {
        /* Fetch and parse the song database */
        appState.songData = await loadSongData();

        /* Mark loading as complete */
        appState.isLoading = false;

        /* --- Step 4: Initialise search index --- */
        /* Build the Fuse.js search index from the loaded song data */
        initSearch(appState.songData);

        /* --- Step 5: Bind search input --- */
        /* Set up search input events (debounced input, clear button, etc.) */
        const container = $('#app-content');
        bindSearchInput(container);

        /* --- Step 6: Handle the initial route --- */
        /* Render the view matching the current URL hash */
        handleRoute();

    } catch (error) {
        /* Song data failed to load: show an error message to the user */
        console.error('[iHymns] Failed to load song data:', error);

        /* Get the content container */
        const container = $('#app-content');

        /* Display a user-friendly error message */
        /* Use textContent for the error.message to prevent XSS */
        container.innerHTML = '';
        const errorContainer = document.createElement('div');
        errorContainer.className = 'text-center py-5';
        errorContainer.innerHTML = `
            <i class="bi bi-exclamation-triangle fs-1 text-danger"></i>
            <h3 class="mt-3">Unable to Load Songs</h3>
            <p class="text-muted">
                The song database could not be loaded. Please check your connection
                and try refreshing the page.
            </p>
            <button class="btn btn-primary mt-2" onclick="location.reload()">
                <i class="bi bi-arrow-clockwise me-1"></i>Retry
            </button>
            <p class="text-muted small mt-3"></p>
        `;
        /* Safely set the error message as text, not HTML */
        errorContainer.querySelector('p.small').textContent = `Error: ${error.message}`;
        container.appendChild(errorContainer);

        /* Stop further initialisation since we have no data */
        return;
    }

    /* --- Step 7: Set up SPA routing --- */
    /* Listen for hash changes (e.g., user clicks back/forward or a link) */
    window.addEventListener('hashchange', handleRoute);

    /* --- Step 8: Service worker --- */
    /* Service worker registration disabled for beta to prevent cache issues.
       The scripts.php component actively unregisters any existing SW.
       Re-enable for production builds. */
    // registerServiceWorker();

    /* --- Step 9: Initialise PWA install banner --- */
    /* Set up the install prompt for users who haven't installed the PWA */
    initInstallBanner();

    /* --- Step 10: Start update checker --- */
    /* Check for app updates every 30 minutes */
    initUpdateChecker(30);

    /* Log successful initialisation */
    console.log('[iHymns] Application initialised successfully.');
}

/* =========================================================================
 * DOM READY — START THE APPLICATION
 * ========================================================================= */

/**
 * Wait for the DOM to be fully loaded before initialising the app.
 * Using 'DOMContentLoaded' ensures all HTML elements are available
 * before we try to access them via querySelector.
 */
document.addEventListener('DOMContentLoaded', init);
