<?php

declare(strict_types=1);

/**
 * iHymns — Apple App Site Association (AASA) responder (#1401)
 *
 * ELI5: This is the "permission slip" Apple's phones/tablets/TVs check
 * before they'll let a tapped ihymns.app link jump straight into the
 * iHymns app instead of opening Safari. It has to live at the exact URL
 * `https://ihymns.app/.well-known/apple-app-site-association`, be plain
 * JSON, and never redirect — so this file IS that response, generated by
 * PHP instead of being a static file, so the Apple Team ID inside it can
 * be swapped without a code deploy.
 *
 * DETAILED: Served at the clean, EXTENSIONLESS path
 * `/.well-known/apple-app-site-association` via the `.htaccess` rewrite
 * added alongside this file (mirrors the existing `/api` → `api.php`,
 * `/sitemap.xml` → `sitemap.xml.php`, `/service-worker.js` →
 * `service-worker.js.php` "hide the .php extension" pattern already used
 * in this docroot). Apple's own fetcher (swcutil / the CDN that seeds
 * Universal Links) requires:
 *   - HTTPS, no redirect (this file is a plain 200 response, no auth,
 *     no maintenance gate — Apple's crawler doesn't carry cookies/session
 *     and must never be shown a 503 maintenance page or a redirect chain);
 *   - Content-Type exactly `application/json` (no `; charset=` suffix —
 *     matches the previous static file's `.htaccess` `ForceType` and
 *     avoids any strictness in Apple's own parser).
 * Reference: https://developer.apple.com/documentation/xcode/supporting-universal-links-in-your-app
 * and the AASA JSON schema at
 * https://developer.apple.com/documentation/bundleresources/applinks
 *
 * TEAM ID SOURCE (strategy §1.7 / owner runbook §A):
 * The Apple Developer Team ID is NOT committed to the repo (it identifies
 * the org's Apple account, not a secret in the security sense, but still
 * account-specific config that shouldn't be hardcoded into source). It is
 * read from `tblAppSettings` under the key `apple_team_id` via the shared,
 * DB-safe `getAppSetting()` helper (`includes/maintenance.php` — the SAME
 * memoized, try/catch-wrapped reader every other runtime flag in this repo
 * uses; rule: never query `tblAppSettings` ad hoc from a page). The
 * Configuration admin page (`manage/configuration.php`, "Apple / native
 * app" card) is where the owner sets it. If the row is missing (fresh
 * install, or before the owner has set it), this file still renders valid
 * JSON using the obviously-fake placeholder `TEAMID` and marks the
 * response with the `X-IHymns-AASA-Status: placeholder` header, so
 * "reachable + valid JSON" (P0's requirement) is true from day one while
 * "actually enables Universal Links" is honestly false until the owner
 * fills in the real value. getAppSetting() already swallows any DB error
 * and returns the default, so a DB outage degrades to the same safe
 * placeholder — this endpoint can never 500 or white-screen.
 *
 * NEVER hand-roll a second reader for this setting or a second AASA
 * responder — this is the ONE file. If a future issue needs a different
 * apple-app-site-association per docroot/channel, extend this file, don't
 * fork it.
 */

require_once dirname(__DIR__) . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'config.php';
require_once dirname(__DIR__) . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'db_mysql.php';
/* maintenance.php is required ONLY for its getAppSetting() helper — this
   endpoint deliberately does NOT call enforceMaintenanceForPublicSite();
   Apple's Universal Link fetcher must always get a plain 200 + valid JSON,
   never a 503 maintenance page. */
require_once dirname(__DIR__) . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'maintenance.php';

/* Content-Type deliberately has NO "; charset=" parameter — Apple's own
   docs + the prior static file's `.htaccess` ForceType both specify the
   bare `application/json` media type for this exact file. */
header('Content-Type: application/json');
header('X-Content-Type-Options: nosniff');
/* Short, non-zero cache lifetime: long enough that Apple's CDN + browsers
   aren't refetching every request, short enough that a Team-ID correction
   the owner makes via /manage/configuration reaches Apple within the hour
   rather than being stuck behind a long-lived cache. Apple's own crawler
   re-fetches on its own schedule regardless of this header. */
header('Cache-Control: public, max-age=3600');

/* getAppSetting() (includes/maintenance.php) is memoized per-request,
   swallows any \Throwable internally, and returns the given default on
   ANY failure (missing table/column on a fresh/un-migrated install, DB
   outage, etc.) — so this try/catch is belt-and-braces, not load-bearing;
   nothing between here and the echo below can throw and white-screen the
   page (repo rule: mysqli runs STRICT + throws, so every optional read
   must be guarded — this endpoint has NO optional read that isn't already
   guarded by getAppSetting() itself). */
$teamId = null;
try {
    $teamId = getAppSetting('apple_team_id', null);
} catch (\Throwable $_e) {
    $teamId = null;
}
$teamId = is_string($teamId) ? trim($teamId) : null;

$isPlaceholder = ($teamId === null || $teamId === '');
/* Obviously-fake placeholder — never a value a real installation would
   collide with, and unmistakable in a debugging session. */
$resolvedTeamId = $isPlaceholder ? 'TEAMID' : $teamId;

/* Bundle id is `app.ihymns` on every Apple platform (strategy §1.1/§1.7) —
   the SAME id for iOS/iPadOS/macOS/tvOS/visionOS is what makes the single
   Universal Purchase App Store record work, so there is only ever ONE
   appID here (no per-platform variants). */
$appId = $resolvedTeamId . '.app.ihymns';

/* `components` (the modern AASA matching format, superseding the flat
 * legacy `paths` array) is an ORDERED list — the FIRST matching entry
 * wins, so exclusions must be listed before the broader patterns they
 * carve out of. `/manage/*` (the admin curation UI) and `/api*` (the JSON
 * API) are real URLs on this same domain but are never a "deep link into
 * app content" — tapping one should always open Safari, never the app.
 *
 * The trailing entry matches the LEGACY `/?page=…&id=…` query-string PWA
 * route shape (pre-dating the clean `/song/*` etc. URLs): Universal Link
 * matching is path-based, so a query parameter can only be expressed via
 * `components`' "?" dictionary — the deprecated flat `paths` format has no
 * way to express this at all, which is the concrete reason this file uses
 * `components` rather than `paths`. `"page": "?*"` requires the `page`
 * query parameter to be present with any non-empty value (Apple's documented
 * query-matching wildcard), so a bare `/` (the home page, no `page` param)
 * does NOT match this entry and is correctly left un-deep-linked.
 */
$components = [
    [
        '/'       => '/manage/*',
        'exclude' => true,
        'comment' => 'Admin curation UI — never a deep-linkable app screen',
    ],
    [
        '/'       => '/api*',
        'exclude' => true,
        'comment' => 'JSON API endpoint — not a navigable page',
    ],
    ['/' => '/song/*',     'comment' => 'Individual song pages'],
    ['/' => '/songbook/*', 'comment' => 'Individual songbook pages'],
    ['/' => '/songbooks',  'comment' => 'Songbooks index'],
    ['/' => '/person/*',   'comment' => 'Credit-person pages'],
    ['/' => '/work/*',     'comment' => 'Work (composition) pages'],
    ['/' => '/setlist/*',  'comment' => 'Setlist pages'],
    ['/' => '/live/*',     'comment' => 'Live Follow / Service Mode join pages'],
    [
        '/'       => '/',
        '?'       => ['page' => '?*'],
        'comment' => 'Legacy ?page=…&id=… PWA fragment routes',
    ],
];

$aasa = [
    'applinks' => [
        /* `apps` must be present and empty for the legacy (pre-iOS 13)
           format some validators still check for. */
        'apps'    => [],
        'details' => [
            [
                /* `appID` (singular) = legacy key (iOS ≤12); `appIDs`
                   (array) = the current documented key. Both point at the
                   same value — belt-and-braces for older OS versions that
                   might still resolve a Universal Link against this
                   domain (the app itself requires OS 26+, but Apple's own
                   AASA-consuming components on other people's older
                   devices are not something this file controls). */
                'appID'      => $appId,
                'appIDs'     => [$appId],
                'components' => $components,
            ],
        ],
    ],
    /* Shared web credentials (AutoFill offers the PWA's saved sign-in on
       the native app's login form) — strategy §1.6. */
    'webcredentials' => [
        'apps' => [$appId],
    ],
    /* Handoff (NSUserActivity webpageURL continuation) — strategy §1.7. */
    'activitycontinuation' => [
        'apps' => [$appId],
    ],
];

if ($isPlaceholder) {
    /* Machine-readable signal for our OWN monitoring/debugging — Apple's
       fetcher ignores unrecognised headers, so this is safe to always send
       and costs nothing when a real Team ID is set (header simply absent). */
    header('X-IHymns-AASA-Status: placeholder-team-id-not-set');
}

echo json_encode($aasa, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
