// swift-tools-version: 6.2
// Package.swift
//
// iHymnsKit — the shared Swift package that holds ~90% of the native Apple
// app's code (see .claude/apple-native-strategy.md §1.1/§1.2). The three thin
// app shells (iHymns/iHymnsTV/iHymnsWatch/iHymnsWidgets, generated by
// XcodeGen from `appApple/project.yml`) each import one or more of the
// library targets below; they may only *compose* this package, never
// reimplement its logic (repo-wide modularity rule, `.claude/CLAUDE.md`).
//
// WHY a local SwiftPM package instead of putting everything in the app
// targets? Xcode projects don't diff well for an AI-agent workflow (binary
// plist / pbxproj), and SwiftPM gives us fast `swift build`/`swift test`
// iteration without ever touching Xcode. XcodeGen owns the *app shell*
// layer (entitlements, asset catalogs, Info.plist) that SwiftPM can't.
//
// LAYERING (strict — a target may only depend on targets *at or below* its
// own row; enforced here by which `dependencies:` arrays list which target,
// and spot-checked by the LOC/quality gates in Scripts/):
//
//   IHFeatures  (screens + view models)
//      ├── IHModels, IHAPI, IHAuth, IHPersistence, IHLive, IHDesign, IHAppSupport, IHLog, IHLiveActivity
//   IHAuth        → IHAPI, IHModels, IHLog
//   IHAPI         → IHModels, IHLog
//   IHPersistence → IHModels                (+ GRDB.swift, external dep)
//   IHLive        → IHAPI, IHModels, IHLog
//   IHLiveActivity → IHModels, IHDesign     (Apple Phase-2 PR-16, #1429 — the
//                     Live Activity/Dynamic Island contract + pure cores +
//                     the iOS-only ActivityKit/AppIntents/WidgetKit UI, all
//                     `#if os(iOS) && canImport(...)`-guarded so this target
//                     itself still cross-compiles for watchOS/tvOS/macOS;
//                     see strategy §2.3)
//   IHAppSupport  → IHModels
//   IHDesign      → (SwiftUI only, no iHymnsKit deps)
//   IHModels      → (no deps — the foundation: Sendable Codable DTOs)
//   IHLog         → (no deps — the foundation: os.Logger/OSSignposter facade;
//                     see #1505 / .claude/live-observability-strategy.md §2.1)
//
// Reference: .claude/apple-native-strategy.md §1.2 (module responsibilities),
// §1.3 (Swift 6 strict concurrency posture), §1.8 (versioning/build).
import PackageDescription

let package = Package(
    name: "iHymnsKit",

    // Min deployment = OS 26 on every Apple platform (owner ground rule,
    // strategy §1.4): "no pre-26 fallback — that audience uses the PWA."
    // This lets every shared view lean on Liquid Glass APIs unconditionally
    // (still availability-guarded in IHDesign as defensive practice).
    platforms: [
        .iOS(.v26),
        .macOS(.v26),
        .tvOS(.v26),
        .watchOS(.v26),
        .visionOS(.v26)
    ],

    products: [
        // One library product per target keeps `import IHModels` etc.
        // working from both the app shells (via XcodeGen's package
        // reference) and from other targets inside this same package.
        .library(name: "IHModels", targets: ["IHModels"]),
        .library(name: "IHLog", targets: ["IHLog"]),
        .library(name: "IHAPI", targets: ["IHAPI"]),
        .library(name: "IHAuth", targets: ["IHAuth"]),
        .library(name: "IHPersistence", targets: ["IHPersistence"]),
        .library(name: "IHLive", targets: ["IHLive"]),
        .library(name: "IHDesign", targets: ["IHDesign"]),
        .library(name: "IHFeatures", targets: ["IHFeatures"]),
        .library(name: "IHAppSupport", targets: ["IHAppSupport"]),
        .library(name: "IHLiveActivity", targets: ["IHLiveActivity"])
    ],

    dependencies: [
        // GRDB.swift — the offline cache engine for IHPersistence (strategy
        // §1.5): FTS5 full-text search + real migrations + Swift 6
        // Sendable support + all six Apple platforms. SwiftData/Core Data
        // were rejected (no FTS5, weaker concurrency story). Pinned to an
        // EXACT version (not a range) so a Kit build is fully reproducible
        // — an upstream GRDB release can't silently change our behaviour
        // between CI runs.
        .package(url: "https://github.com/groue/GRDB.swift.git", exact: "7.11.1")
    ],

    targets: [
        // MARK: - IHTestFixtures (test-only support target, no product —
        // depended on directly by the test targets below)
        //
        // Holds the LIVE-RECORDED contract fixtures (#1396,
        // `Tests/Fixtures/README.md`) as bundled SwiftPM resources, plus one
        // tiny loader (`ContractFixtures`) so `IHModelsTests` and
        // `IHAPITests` both read the exact same JSON files via
        // `Bundle.module` instead of each re-implementing its own resource
        // lookup — the repo's modularity rule ("if a shared module already
        // exists, reuse it — do not duplicate") applies just as much to
        // test infrastructure as to product code. `path:` points directly
        // at `Tests/Fixtures/` (not a `Sources/`-rooted default) so the
        // fixture JSON lives exactly where #1396 was asked to record it,
        // with the loader `.swift` file alongside it.
        .target(
            name: "IHTestFixtures",
            path: "Tests/Fixtures",
            exclude: ["README.md"],
            resources: [
                .copy("songs_index.json"),
                .copy("song_detail.json"),
                .copy("songbooks.json"),
                .copy("song_links.json"),
                .copy("related_songs.json"),
                .copy("song_of_the_day.json"),
                // Apple Phase-2 PR-10 (#1426, #1427) — Live Follow / Service
                // Mode wire-contract fixtures (`README.md`'s own provenance
                // block: 4 live-recorded negatives + 5 code-derived-and-
                // marked positives).
                .copy("live_follow_join_not_found.json"),
                .copy("live_follow_poll_inactive.json"),
                .copy("live_follow_join.json"),
                .copy("live_follow_poll_changed.json"),
                .copy("service_join_not_active.json"),
                .copy("service_poll_inactive.json"),
                .copy("service_join.json"),
                .copy("service_poll_changed.json"),
                .copy("service_poll_unchanged.json"),
                // Apple Phase-2 PR-15 (#1428) — the tvOS projector's
                // `role:"projector"` join shape (`pollIntervalMs:1000`).
                .copy("service_join_projector.json"),
                // Apple Phase-2 PR-16 (#1429) — the Live Activity
                // `ActivityContentState` contract fixture: the SAME file
                // `includes/live_activity_push.php`'s PHP-side test reads
                // (`tests/php/test-apns-live-activity-push.php`), so the two
                // sides can never silently drift apart (that PHP file's own
                // header explains the byte-shape guarantee).
                .copy("live_activity_content_state.json")
            ],
            swiftSettings: sharedSwiftSettings
        ),

        // MARK: - IHAPITestSupport (test-only support target, no product —
        // depended on directly by every test target below that needs to
        // mock networking)
        //
        // Holds `MockURLProtocol` (#1397's `URLProtocol`-stubbing harness)
        // and `LockedCounter` (a manually-synchronized counter safe to
        // capture in a `@Sendable` mock request handler). Originally lived
        // ONLY inside `IHAPITests` — #1398/#1399 need the exact same mock
        // transport from `IHAuthTests` (`SessionController`'s `auth_login`/
        // `auth_logout` tests) and `IHFeaturesTests` (`AppRootViewModel`'s
        // catalogue-load tests), so it moved here rather than being
        // copy-pasted into each — the repo's modularity rule ("if a shared
        // module already exists, reuse it — do not duplicate") applies just
        // as much to test infrastructure as to product code, and mirrors
        // exactly how `IHTestFixtures` above is already shared the same way.
        .target(
            name: "IHAPITestSupport",
            path: "Tests/IHAPITestSupport",
            swiftSettings: sharedSwiftSettings
        ),

        // MARK: - IHModels (foundation layer — zero iHymnsKit deps)
        .target(
            name: "IHModels",
            swiftSettings: sharedSwiftSettings
        ),
        .testTarget(
            name: "IHModelsTests",
            dependencies: ["IHModels", "IHTestFixtures"],
            swiftSettings: sharedSwiftSettings
        ),

        // MARK: - IHLog (foundation layer, beside IHModels — zero
        // iHymnsKit-internal deps; only system frameworks: `os` (Logger +
        // OSSignposter) and CryptoKit (SHA-256 for `IHLogSanitize`), never
        // an external SwiftPM package)
        //
        // #1505 (`.claude/live-observability-strategy.md` §2.1). Its own
        // leaf target rather than folded into `IHModels` (wrong layer —
        // `IHModels` is pure Sendable DTOs with no side effects) or
        // `IHAppSupport` (the strategy doc is explicit: that would drag the
        // analytics-adjacent module into every target that just wants to
        // log). `IHAPI`/`IHAuth`/`IHLive` import it directly below;
        // `IHFeatures` gets it both transitively through those and directly
        // (its own view models log too).
        .target(
            name: "IHLog",
            swiftSettings: sharedSwiftSettings
        ),
        .testTarget(
            name: "IHLogTests",
            dependencies: ["IHLog"],
            swiftSettings: sharedSwiftSettings
        ),

        // MARK: - IHAPI (→ IHModels, IHLog)
        .target(
            name: "IHAPI",
            dependencies: ["IHModels", "IHLog"],
            swiftSettings: sharedSwiftSettings
        ),
        .testTarget(
            name: "IHAPITests",
            dependencies: ["IHAPI", "IHModels", "IHTestFixtures", "IHAPITestSupport"],
            swiftSettings: sharedSwiftSettings
        ),

        // MARK: - IHAuth (→ IHAPI, IHModels, IHLog)
        .target(
            name: "IHAuth",
            dependencies: ["IHAPI", "IHModels", "IHLog"],
            swiftSettings: sharedSwiftSettings
        ),
        .testTarget(
            name: "IHAuthTests",
            // #1398: `SessionController` now composes a real `APIClient` —
            // its tests need `IHAPI` directly (to construct one against a
            // mocked `URLSession`) and `IHAPITestSupport` for that mock.
            dependencies: ["IHAuth", "IHAPI", "IHAPITestSupport"],
            swiftSettings: sharedSwiftSettings
        ),

        // MARK: - IHPersistence (→ IHModels, + GRDB)
        .target(
            name: "IHPersistence",
            dependencies: [
                "IHModels",
                .product(name: "GRDB", package: "GRDB.swift")
            ],
            swiftSettings: sharedSwiftSettings
        ),
        .testTarget(
            name: "IHPersistenceTests",
            dependencies: ["IHPersistence", "IHModels"],
            swiftSettings: sharedSwiftSettings
        ),

        // MARK: - IHLive (→ IHAPI, IHModels, IHLog)
        //
        // #1420 UPDATE — `IHLive/LANRemote` (the peer-to-peer TV-remote
        // sub-module added alongside the pre-existing server-mediated
        // `LiveFollowEngine`, strategy §1.2/§2.4) reuses `IHModels.SongID`
        // for its `selectSong`/`prepare`/`state` message fields rather than
        // re-validating the `<letters>-<digits>` shape itself (CLAUDE.md
        // rule #27's "if a shared module already exists, reuse it" applied
        // to Swift, not just PHP) — so this target now depends on
        // `IHModels` directly, not merely "transitively through IHAPI"
        // (Swift import visibility requires every target that writes
        // `import IHModels` to list it explicitly; SwiftPM does not grant
        // transitive import access the way it links transitive binaries).
        .target(
            name: "IHLive",
            dependencies: ["IHAPI", "IHModels", "IHLog"],
            swiftSettings: sharedSwiftSettings
        ),
        .testTarget(
            name: "IHLiveTests",
            // #1420: the new `LANRemoteTests` suite constructs `SongID`
            // fixtures directly for IHRP message round-trip tests. PR-10
            // (#1426, #1427) adds `IHAPI` (constructing a real `APIClient`
            // against a mocked `URLSession`) + `IHAPITestSupport`
            // (`MockURLProtocol`) for the `ServerLive/` engine-loop suites.
            dependencies: ["IHLive", "IHModels", "IHAPI", "IHAPITestSupport"],
            swiftSettings: sharedSwiftSettings
        ),

        // MARK: - IHDesign (no iHymnsKit deps beyond SwiftUI)
        //
        // `resources: [.process("Resources/Colors.xcassets"), ...]` (#1438) —
        // the ONE Asset Catalog `IHColorTokens` reads its Any/Dark/High-
        // Contrast colour sets from (`Color("Accent", bundle: .module)`).
        // `.process` (not `.copy`) so SwiftPM invokes `actool` to compile
        // it the same way Xcode would for an app target's own catalog —
        // `IHTestFixtures`'s `.copy(_:)` precedent (Package.swift's other
        // `resources:` user) is for raw JSON, which needs no compilation.
        //
        // `.copy("Resources/Fonts")` (#1412 FONT-PENDING completion) bundles
        // the four OpenDyslexic OTFs + their `OpenDyslexic-OFL.txt` licence
        // as-is under `Bundle.module`'s `Fonts/` subdirectory — a raw font
        // file needs no `actool`-style compilation, so `.copy` (not
        // `.process`) is the correct resource kind here, mirroring
        // `IHTestFixtures`'s reasoning above rather than `Colors.xcassets`'s.
        // `IHFonts.registerBundledFonts()` (`IHFonts.swift`) is what reads
        // this directory back out at runtime via `Bundle.module.urls(
        // forResourcesWithExtension:subdirectory:)`.
        .target(
            name: "IHDesign",
            resources: [
                .process("Resources/Colors.xcassets"),
                .copy("Resources/Fonts")
            ],
            swiftSettings: sharedSwiftSettings
        ),
        .testTarget(
            name: "IHDesignTests",
            dependencies: ["IHDesign"],
            swiftSettings: sharedSwiftSettings
        ),

        // MARK: - IHLiveActivity (→ IHModels, IHDesign)
        //
        // Apple Phase-2 PR-16 (#1429; strategy §2.3) — the Live Activity/
        // Dynamic Island "now singing" card. Holds the wire-contract DTOs
        // (`NowSingingActivityAttributes`/`ContentState`), the three pure
        // cores (`NowSingingActivityReducer`/`NowSingingSectionNavigator`/
        // `NowSingingIntentBridge`) every platform in `Package.swift`'s
        // `platforms:` list builds, AND the iOS-only ActivityKit/AppIntents/
        // WidgetKit UI (`NowSingingActivityController`/`NowSingingIntents`/
        // `NowSingingLiveActivityWidget`) — every one of THOSE types is
        // `#if os(iOS) && canImport(...)`-guarded internally so this ONE
        // target still cross-compiles cleanly for watchOS/tvOS/macOS/
        // visionOS (only the pure cores + the unguarded
        // `NowSingingActivityControlling` protocol survive the `#if` on
        // those platforms), mirroring `IHLive/LANRemote`'s own "one target,
        // platform-guarded internals" shape rather than splitting into a
        // second SwiftPM target per platform. `IHDesign` (not just
        // `IHModels`) is a direct dependency because the Live Activity/
        // Dynamic Island UI (`NowSingingLiveActivityWidget.swift`) reads
        // `IHColorTokens` the same way every other iHymnsKit UI surface
        // does — never a duplicated colour literal.
        .target(
            name: "IHLiveActivity",
            dependencies: ["IHModels", "IHDesign"],
            swiftSettings: sharedSwiftSettings
        ),
        .testTarget(
            name: "IHLiveActivityTests",
            dependencies: ["IHLiveActivity", "IHTestFixtures"],
            swiftSettings: sharedSwiftSettings
        ),

        // MARK: - IHFeatures (→ everything — the composition root for screens)
        .target(
            name: "IHFeatures",
            dependencies: [
                "IHModels",
                "IHAPI",
                "IHAuth",
                "IHPersistence",
                "IHLive",
                "IHDesign",
                "IHAppSupport",
                "IHLog",
                "IHLiveActivity"
            ],
            swiftSettings: sharedSwiftSettings
        ),
        .testTarget(
            name: "IHFeaturesTests",
            // #1399: the catalogue/detail view-model tests decode the same
            // committed fixtures `IHAPITests`/`IHModelsTests` use, against
            // the same `MockURLProtocol` mock transport — hence
            // `IHTestFixtures`/`IHAPITestSupport` alongside the existing
            // engine dependencies. PR-16 (#1429) adds `IHLiveActivity` for
            // `AppRootViewModel+LiveActivity.swift`'s spy-controller tests.
            // #1415 adds `IHAppSupport` directly (not just transitively
            // through `IHFeatures`) — `IntentRoutingTests`/
            // `SongEntityResolverTests`/`AppRootViewModelSystemIndexTests`
            // reference `DeepLinkRouter`/`SpotlightIndexEntry`/
            // `SpotlightIndexing`/`SpotlightIndexer` types directly, which
            // needs this test target to `import IHAppSupport` itself (SwiftPM
            // doesn't grant transitive import access the way it links
            // transitive binaries — the same reasoning `IHLive`'s own
            // `Package.swift` comment documents for its `IHModels` addition).
            dependencies: [
                "IHFeatures", "IHAPI", "IHAuth", "IHLive", "IHModels", "IHPersistence",
                "IHAppSupport", "IHTestFixtures", "IHAPITestSupport", "IHLiveActivity"
            ],
            swiftSettings: sharedSwiftSettings
        ),

        // MARK: - IHAppSupport (→ IHModels)
        .target(
            name: "IHAppSupport",
            dependencies: ["IHModels"],
            swiftSettings: sharedSwiftSettings
        ),
        .testTarget(
            name: "IHAppSupportTests",
            dependencies: ["IHAppSupport", "IHModels"],
            swiftSettings: sharedSwiftSettings
        )
    ]
)

// MARK: - Shared Swift 6 strict-concurrency settings
//
// `.swiftLanguageMode(.v6)` opts every target into full Swift 6 semantic
// checking (not just the SDK's ABI-stable mode). `StrictConcurrency` is also
// forced `complete` here at the SwiftPM layer so `swift build`/`swift test`
// enforce exactly what Xcode's `SWIFT_STRICT_CONCURRENCY = complete` build
// setting enforces for the app shells (kept in sync with
// `Config/Shared.xcconfig`) — see strategy §1.3.
private let sharedSwiftSettings: [SwiftSetting] = [
    .swiftLanguageMode(.v6),
    .enableUpcomingFeature("StrictConcurrency")
]
